### ISSUE TITLE
Ajax Upload Scenario 6

### ISSUE THREAD

**Issue by GBraL** [kartik-v/bootstrap-fileinput#1001]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. https://gist.github.com/GBraL/24f487734f969904fc75fc97d37d1364
2.
3.

## Expected behavior and actual behavior

After I upload images using sample "AjaxUpload Scenario 6" (http://plugins.krajee.com/file-input-ajax-demo/6) the icon "hamburger" used to drag-drop image to sort it isn't showed. In your place is shoed "check" icon about success upload.

I was expecting to sort image after upload.

## Environment

Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [X] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin]

P.S.: If my question is not relative to a issue I'd like to apologize for the mistake.

**Comment by kartik-v** [comment]
It is obvious because you have not written you server code correctly to send the `initialPreview`, `initialPreviewConfig`. The server code must return the above properties as a JSON object as mentioned in the demo within your file upload server action.

As reiterated in the documentation: 

- **Sorting/Drag drop is ONLY ALLOWED for thumbnails in the initial preview.**
- For the specific example ajax scenario 6, it is a variation of ajax scenario 5. So refer [ajax scenario 5](http://plugins.krajee.com/file-input-ajax-demo/5) which mentions a sample server code (PHP) to return the `initialPreview`, `initialPreviewConfig`.

**Comment by GBraL** [comment]
Thank you.
