### ISSUE TITLE
Bootstrap3.x  --> Boostrap 2.x

### ISSUE THREAD

**Issue by liuqiao1** [kartik-v/bootstrap-fileinput#1052]
is there any possible that fileinput can support Bootstrap2.x?    I really need this now~
because my project is based on boostrap2,  if I forcely inlude boostrap3.x into my project,
it will cause pages are not keep  same style.

**Comment by kartik-v** [comment]
It was built for BS-3 although the plugin gives you the ability to override the styles and also gives you various properties as templates to override the markup specific to fit any CSS framework.

Currently focus will be to move forward on Bootstrap and version 4.x support beyond 3.x rather than going back to any older versions.
