### ISSUE TITLE
can't rearrange the preview image before upload

### ISSUE THREAD

**Issue by csthink** [kartik-v/bootstrap-fileinput#1054]
After add image I want re-arrange the preview image , I have tried to use sortable plugin ,I can re-arrange the preview image ,but when I submit , the server receive old sort image not new sort , Could you tell me how to use sortable plugin before uploaded . Thanks!

**Comment by kartik-v** [comment]
The plugin does not allow you to rearrange thumbnails before upload - there are many reasons - few of them:

- it will directly conflict with the order of items in initial preview - while the order of items not yet uploaded is still volatile and will only be certain after user has uploaded files
- since there is no control on what thumbnail will be uploaded and when by the user 
- what happens when there are validation errors (like allowed file type, max file size, count etc.) 
- what happens when user adds more files at a random order 
- what happens when you receive upload errors in few thumbnails and how will they be merged

 You can try designing it separately for your app - by taking care of all these validations.
