### ISSUE TITLE
SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by ssvdreyf** [kartik-v/bootstrap-fileinput#1076]
When loading documents, this is a bug, although it loads everything:

name_document.doc: SyntaxError: Unexpected token u in JSON at position 0
uploads/Payments/

help resolve it!

**Comment by kartik-v** [comment]
Cannot reproduce your issue. Please share a JS Fiddle or resubmit the issue with a proper example to reproduce.

**Comment by gediminaskv** [comment]
I had the same issue. It was due to `file_get_contents` and `file_put_contents` PHP functions which I ussed to store JSON data to file. While uploading many files at a time it messed up.

I've implemented Method 1 from https://www.sitepoint.com/community/t/how-to-overwrite-a-file-atomically/268982/21 and it works well.
