### ISSUE TITLE
Looping fileunlock event when using AJAX

### ISSUE THREAD

**Issue by zebub** [kartik-v/bootstrap-fileinput#110]
I'm experiencing strange behavior when performing an `AJAX` request in a `fileunlock` event.

```js
$('#upload').on('fileunlock', function (event, filestack, extraData) {
    $.ajax();
});
```

This causes the `fileunlock` event to trigger when the `AJAX` request completes, in turn causing a loop.

**Comment by kartik-v** [comment]
This is because the unlock event is called within `ajaxStop`... and if you trigger another ajax inside unlock, its calling itself on ajaxStop.

If you upgrade to the latest release, the plugin uses some flags to check the `locked` status. So you should not face this.

For advanced usage and your info.. the updated plugin also uses namespaces to bind `ajaxStop` (i.e. `ajaxStop.kvfileinput` instead of `ajaxStop` - so one can unbind the `.kvfileinput` for advanced ajax calls).
