### ISSUE TITLE
Reset of the file input plugin

### ISSUE THREAD

**Issue by sandeep-kgp** [kartik-v/bootstrap-fileinput#1104]
Hi Kartik,

Can you please help with the form resetting ? After the file is uploaded and the form is submitted I need to reset the plugin to its default value as if no file has been uploaded yet and  keep the settings same as was like when the page was loaded. tried fileinput('reset'), fileinput('clear') and fileinput('refresh') too but nothing is working perfectly ..  With clear it does the most but still see the empty box and the upload button as if somefile is present in the cache which i can upload.
Thanks,
Sandeep.

**Comment by itsikhar** [comment]
Hi Kartik,

I'm also facing this issue with "reset", "refresh" and "destory" functions.

I have a custom form and when the ajax call response I tried to reset the fileinput.
the method not react to this action. seems like it's because the ID of the element is changed during the plugin initialization.

Please your help :)

**Comment by kartik-v** [comment]
Provide your own unique id to the file input markup.

**Comment by itsikhar** [comment]
I did it, but after the input initizlize the input file id is gone..

**Comment by kartik-v** [comment]
Unfortunately your issue(s) cannot be reproduced. You may want to have a look at your javascript code and HTML markup.

If you can reproduce the issue, please share a JS Fiddle or similar to check. Will reopen this issue then,
