### ISSUE TITLE
filepreremove function return empty event.target.files when we remove newly uploaded images.  

### ISSUE THREAD

**Issue by pujarasanni027** [kartik-v/bootstrap-fileinput#1192]
// When we click on delete button it's works first image, for second image it's(event.target.files) become null for newly uploaded images.

```
.on('filepreremove', function(event, id, index) {
                var deletedFileName = event.target.files[index].name;
});
```

// Please any suggestion or i am missing something to the code.

**Comment by kartik-v** [comment]
You cannot get files for deletion separately that way by reading the native file input ... not sure why you are doing that... Since the file input cannot be modified selectively as mentioned ... You can maybe use the Ajax mode of file upload and manipulation whereby you can get the files via the plugin `getFileStack`method

**Comment by pujarasanni027** [comment]
Thanks Kartik - v , 
Actiually my project is in Angular 2 and i am integrating this control in that.
its working for newly uploaded images by **getFileStack** ., 

Just wanna ask one question
Can i get latest Re-Ordered List on any Submit button from this control?

**Comment by pujarasanni027** [comment]
Thanks Kartik,

working on re-order/arrange images and maintaining display sequence.,
so can i get re-arranged images list (order by) when click on any submit button .

thorough which we can easily manage it server side also.
