### ISSUE TITLE
I got an error after upload image

### ISSUE THREAD

**Issue by yua3** [kartik-v/bootstrap-fileinput#1238]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by kartik-v** [comment]
Before filing issues - please [read guidelines](https://github.com/kartik-v/bootstrap-fileinput/blob/master/.github/CONTRIBUTING.md),  and please read the [plugin documentation](http://plugins.krajee.com/file-input) on the [pre-requisites for ajax uploads](http://plugins.krajee.com/file-input#ajax-uploads) and the response format expected by the plugin for ajax uploads.

Also search for duplicate issues and read them before posting. Your issue is duplicate to #301, #538, #107, #622 for example.

Your [question is answered in this webtip](http://webtips.krajee.com/question/json-syntax-error-bootstrap-fileinput/).
