### ISSUE TITLE
Can not upload form data unless one or more files are selected

### ISSUE THREAD

**Issue by dalamberts** [kartik-v/bootstrap-fileinput#124]
I set uploadExtraData: true, uploads work fine as long as I have a file attached.  However, there are many cases where I need to submit the form without and files being attached.

	$("#file4").fileinput({
//showUpload: false,
showCaption: false,
showRemove: false,		
browseClass: "btn btn-primary",
fileType: "any",
browseIcon: '',
browseLabel: 'Select files',
dropZoneEnabled: true,
dropZoneTitle: 'Drag &amp; drop files here',		
	    maxFileCount: 10,
			uploadUrl: 'upload_files_krajee.php',
			uploadAsync: false,
			uploadExtraData: function () {
		    var s = $('#add_form').serializeArray();		    
		    return s;
			},		
			layoutTemplates: {
		    actions: '<div class="file-actions">\n' +
		        '<div class="file-footer-buttons">\n' +
		        '{delete}{other}' +
		        '</div>\n' +
						'<div class="file-upload-indicator" tabindex="-1" title="{indicatorTitle}">{indicator}</div>' +		        
		        '<div class="clearfix"></div>\n' +
		        '</div>'
			}      
	});

**Comment by kartik-v** [comment]
You need to write a bit of your own javascript for this. You can trap one of the events like `filepreupload` to check and submit another POST request or whatever you need.

**Comment by dalamberts** [comment]
Thank you for your reply.

With all due respect, considering the fact that often times when you upload a file (via ajax) it also has other form fields associated with it, I would see this as expected behavior of the plugin, not something that I should have to write extra code.

Is it possible this could be included in the next release?

**Comment by kartik-v** [comment]
Will need to check on this later as an enhancement. The plugin's core feature has been to process file selection and preview. With ajax based upload file ability, the option of sending extra data was an useful addition - but since the focus has been on file upload --- there has been no thought directly on validating the extra data. 

Since the use cases can be many - will need to see how it can be generalized. Certainly would not  want to address all use cases of data manipulation with this plugin. The plugin events have been designed to trigger specifically for such a case... so that developers can extend and build various use case scenarios.

Will check on this later and record an enhancement to see when I can look into it when I get time. Feel free to input your thoughts or enhance with a PR.

**Comment by dalamberts** [comment]
If I just called the upload function inside the plugin, would that work?  What would be the syntax to make that call?

**Comment by kartik-v** [comment]
I am creating an enhancement to allow submission of extra data even if there are no files.

**Comment by dalamberts** [comment]
Thank you for including this feature.  Unfortunately, it does not work if I submit a form with no attached file.  Is there a new option I need to set?

**Comment by kartik-v** [comment]
Resolved via #173 for ajax uploads.

For normal form submission you will receive your other form data irrespective of files selected in file input.
