### ISSUE TITLE
Customize "Submit" button

### ISSUE THREAD

**Issue by emresaracoglu** [kartik-v/bootstrap-fileinput#1257]
Hello,

Firstlly thank you for script, it's great! I have a question. I've looked at every site for days but I'm afraid I didn't find it.

I have a classic form and I use Fileınput in the form. Submit button, I want to use it with the form's own button. 

[JSFiddle](https://jsfiddle.net/emresaracoglu/f97humsd/)

How can I do that?
Thank you.

**Comment by emresaracoglu** [comment]
Thank you for answer. @kartik-v 
I'm afraid I didn't succeed. Please is it possible to give a simple example of JSFiddle?

**Comment by emresaracoglu** [comment]
@kartik-v

**Comment by kartik-v** [comment]
Am not sure you have gone through the plugin docs and demos. Please go through them.

The ISSUE WITH YOUR CODE is specifically because you have added the CSS Class <code>file</code> to your input markup.  Read the {usage section of the plugin](http://plugins.krajee.com/file-input#usage). **You must NOT add the CSS class if you are initializing the plugin via Javascript and that is the reason your markup is getting messed up.**

There are usage examples without upload URL - you can look at the fileinput plugin [advanced usage demos](http://plugins.krajee.com/file-advanced-usage-demo) examples 1 to 10 which all are without <code>uploadUrl</code> and for form submission. You just need to render them inside a form with a submit button.

**Comment by emresaracoglu** [comment]
Yes, I did I can successfully upload a photo but If I want to upload more than one photo, I getting  "Please choose at least one file " warning.

What could be the reason for this?

```
$("#images").fileinput({
		'language': 'tr',
		'minFileCount': 1,
		'showCaption': false,
		'showUpload': false,
		'browseOnZoneClick': true,
		'previewFileType': 'any',
		'allowedFileExtensions': ["jpg", "png", "gif", "jpeg"]
	});
```

_Version: 4.4.8_

**Comment by emresaracoglu** [comment]
Yes, I did I can successfully upload a photo but If I want to upload more than one photo, I getting  "Please choose at least one file " warning.

What could be the reason for this?

```
$("#images").fileinput({
		'language': 'tr',
		'minFileCount': 1,
		'showCaption': false,
		'showUpload': false,
		'browseOnZoneClick': true,
		'previewFileType': 'any',
		'allowedFileExtensions': ["jpg", "png", "gif", "jpeg"]
	});
```

_Version: 4.4.8_

cc @kartik-v

**Comment by emresaracoglu** [comment]
I've been using it smoothly for the last few days. Again **thank you** for your time and this repo.

cc @kartik-v
