### ISSUE TITLE
SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by genc6541** [kartik-v/bootstrap-fileinput#127]
Hello , when I try upload image I m getting this erro please help.

**Comment by kartik-v** [comment]
Its an error on your server code returning an invalid json format for your upload response. Debug it with firebug or javascript console and resolve to return a right JSON format.

**Comment by MasterMindNET** [comment]
Good day everyone!

Is it okay if i get error `Uncaught ReferenceError: typeahead_7864e59a is not defined`
and one more `Uncaught SyntaxError: Invalid or unexpected token kartik typeahead`

if i return array with value like this: `<script>alert('mummy');</script>`

or it's my fault to save such content?
I'm interested in this, and I would like to know it, in order to avoid such mistakes in the feature.

Any help will be appreciated!
