### ISSUE TITLE
bootstrap-fileinput: "fileupload": Error loading the piexif.js library.

### ISSUE THREAD

**Issue by AJavierSanchez** [kartik-v/bootstrap-fileinput#1286]
first of all: **GREAT JOB!!!** 

## Steps to reproduce the issue
this is my plugin initialization:

     $("#fileupload").fileinput({
          language : 'es',
          showUpload:true, 
          uploadUrl: 'someurl',
          allowedFileType : ['image'],
          allowedFileExtensions : ['jpg','jpeg','png'],
          previewFileType :'image',
          showCaption: true,
          dropZoneEnabled: true,
          showRemove: true,
          maxFileCount: 6,
          maxFileSize: 100000,
          browseClass: "btn btn-success",
          browseLabel: "Elegir Imagen/es",
          browseIcon: "<i class=\"fa fa-file-image-o\"></i> ",
          removeClass: 'btn btn-danger',
          removeTitle: 'Borrar Imagen',      
          removeLabel: "orrar",
          removeIcon: "<i class=\"fa fa-trash-o\"></i> ",
          uploadClass: "btn btn-info",
          uploadLabel: "Subir",
          uploadIcon: "<i class=\"fa fa-upload\"></i> "
        });

this is the html part, 

`<input id="fileupload" type="file" name="file" multiple>`

I know that I've should named it as file[], but the server which receives the files expect name to be file. And it doesn't produce any error.
     

## Expected behavior and actual behavior

The plugin seems to work correctly, but in the chrome console I've get the piexif.js error every time I upload a file. I'm just reporting it.

## Environment
Browsers

- [X] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [X] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.3.1
- bootstrap-fileinput version: 4.5.0

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [X] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
This happens because `piexif.js` is required to be loaded for auto orientation of JPEG images in preview - and is controlled by the property [`autoOrientImage`](http://plugins.krajee.com/file-input/plugin-options#autoOrientImage) - this property defaults to `true`. If you do not wish to load piexif.js or do not need auto orientation - set `autoOrientImage`](http://plugins.krajee.com/file-input/plugin-options#autoOrientImage) to `false`.

**Comment by AJavierSanchez** [comment]
oopss... excuse me. I thought I've loaded piexif.js. But. shouldn't this option defaults to false as it depends on an extra script?. Once again, thank you, excuse me and congratulations on a great, great job!!

**Comment by kartik-v** [comment]
Will note an enhancement for defaulting [`autoOrientImage`](http://plugins.krajee.com/file-input/plugin-options#autoOrientImage) to `false`.

**Comment by AJavierSanchez** [comment]
Hi, the problem remains although I put the autoOrientImage to false.

**Comment by kartik-v** [comment]
Please share a JS Fiddle to reproduce your issue to understand.

**Comment by hebriels** [comment]
Same problem. When adding a .pdf file

**Comment by nadiacq** [comment]
Same problem :(

**Comment by kartik-v** [comment]
Folks - note [as mentioned in this comment](https://github.com/kartik-v/bootstrap-fileinput/issues/1286#issuecomment-412101012) that this depends on how you are configuring this in your app and please check your browser console to understand the issue and configure your app accordingly. I am not sure what the issue is - so please share a JS fiddle. You can cross check the [plugin demo pages](http://plugins.krajee.com/file-input/demo#preview-management) where piexif.js is not loaded in any of the demos except the [file image management demo](http://plugins.krajee.com/file-image-management-demo) where piexif.js is used.

There are 2 reasons where piexif.js is needed and you must load it on your page if you have configured your app accordingly:

1. The first reason is when you have `autoOrientImage` set to `true`
2. The second reason is when you are using the image resize capability of the plugin

Check your configuration and if you have an issue please provide a JS Fiddle to reproduce your issue.

**Comment by AJavierSanchez** [comment]
Here's the example. Just add an image and check the console. 
https://jsfiddle.net/thejavo/29586z7d/13/

**Comment by AJavierSanchez** [comment]
Of course if I load the piexif.js file, the problem disappears, but I don't need it.

**Comment by kartik-v** [comment]
Thanks for the fiddle ... will check

**Comment by kartik-v** [comment]
Resolved with latest update.

**Comment by AJavierSanchez** [comment]
pleased to help!

**Comment by hebriels** [comment]
Yes Thanks!

**Comment by jonasva** [comment]
same here, error appears when selecting a new image.

**Comment by kartik-v** [comment]
Get the latest code from dev-master (v4.5.1) - it will be tagged with new release soon.

**Comment by jonasva** [comment]
Ok thx, are you going to include it in the sass branch as well? (I'm using that one)

**Comment by kartik-v** [comment]
yes

**Comment by brunomcuesta** [comment]
Thanks!

**Comment by brunomcuesta** [comment]
I updated the version to 4.5.1 using Bower and the error persists after selecting an image to upload.

**Comment by newscloud** [comment]
Using v4.5.2 

Also seeing:
 bootstrap-fileinput: "photo-attachment_1": Error loading the piexif.js library.

piexif.js shows it is loaded in source on the page from your plugin

**Comment by jhonhenrybernal** [comment]
The first example worked for me

**Comment by kuntur-studio** [comment]
I'm using version 5.0.1 and have the same problem.

**Comment by kartik-v** [comment]
Read about [autoOrientImage](http://plugins.krajee.com/file-input/plugin-options#autoOrientImage)  property in docs for 5.x. Either load the piexif library or set the above property explicitly to false.

**Comment by kuntur-studio** [comment]
Yes I did, I thought that the property was false by default.
Sorry.
