### ISSUE TITLE
拖拽文件时，$("#file").val() 获取文件路径为空。

### ISSUE THREAD

**Issue by cabqzy** [kartik-v/bootstrap-fileinput#1363]
拖拽文件时，$("#file").val() 获取文件路径为空。点击选择正常

**Comment by kartik-v** [comment]
You will not be able to read the files selected via `$('#file').val()`  - since the native file input cannot be manipulated via javascript - so the files dragged cannot be read via that.

You need to use the [getFileStack](http://plugins.krajee.com/file-input/plugin-methods#getFileStack) method to read the stack of files selected.
