### ISSUE TITLE
After i delete one preupload file the other files are not subbmited

### ISSUE THREAD

**Issue by arditimeri6** [kartik-v/bootstrap-fileinput#1392]
I am using Bootstrap-fileinput and its really cool!

But i have a problem when i delete one preupload file.

When i select multiple files and submit them everything is working fine.

But when im  selecting for example 4 files and after that im deleting one of them.
Then when i submit the form, the other 3 files are not getting submitted

Here is the code:

```
$("#fileUpload").fileinput({
            theme: 'fa',
            uploadUrl: "/imageUpload",
            allowedFileExtensions: ['jpg', 'png', 'jpeg'],
            overwriteInitial: false,
            maxFileSize:2000,
            maxFilesNum: 10,
            fileActionSettings: {showUpload: false},
            showUpload: false,
            slugCallback: function (filename) {
                return filename.replace('(', '_').replace(']', '_');
            }
        })
```

**Comment by kartik-v** [comment]
Read the documentation and [usage modes of the plugin](http://plugins.krajee.com/file-input#usage-modes). The error you are facing is because you are trying to combine form submission with ajax mode (using `uploadUrl`) - which as stated in the documentation WILL NOT WORK. Either use ajax based submission by setting the `uploadUrl` OR if you wish to use form based submission then use it without `uploadUrl`. Note that the form based submission mode has lesser features than ajax based submission. Refer the [comparison of features between the 2 modes](http://plugins.krajee.com/file-input#modes-compared).
