### ISSUE TITLE
Remove one image but without ajax

### ISSUE THREAD

**Issue by fouad1994** [kartik-v/bootstrap-fileinput#1407]
How to delete one image from multiple from initial preview or the new selections but without ajax I just want to store images config deleted in array and update it from php on submit form Can I find some help?

**Comment by kartik-v** [comment]
The default delete button uses only ajax based delete. Since your use case is to do a customized action - for your use case you can do the following:

- Hide default delete button by setting `showRemove` to `false` in [fileActionSettings](http://plugins.krajee.com/file-input/plugin-options#fileActionSettings)
- Implement your own custom delete action by setting button markup within [otherActionButtons](http://plugins.krajee.com/file-input/plugin-options#otherActionButtons)
- Write your javascript on the custom button markup (e.g. listening to the click action on button css class selector).
