### ISSUE TITLE
Remove File before form submit

### ISSUE THREAD

**Issue by apilavakis** [kartik-v/bootstrap-fileinput#142]
I decided to not go with the ajax upload in my implementation and i noticed that even though i press the 'recycle bin' icon on the thumbnail and it is correctly removed from the preview, when i submit the form it is still included in the Request.Files.

As a result, even though the user chose not to submit the specific image it is still saved because it exists in the Request.Files.

**Comment by kartik-v** [comment]
Cannot replicate your case. How are you configuring the plugin?

**Comment by apilavakis** [comment]
this is my configuration

            <input id="fileinput" name="listingImages" class="file" type="file" multiple="multiple" data-preview-file-type="image" data-show-remove="false" data-show-upload="false" data-upload-url="#" data-max-file-size="1000" data-max-file-count="5">

**Comment by kartik-v** [comment]
The problem is that you are providing `data-upload-url` which is triggering the ajax action. You should not be passing that property since you mentioned you are using traditionaly form-submit.

**Comment by apilavakis** [comment]
In which case i am not able to remove one by one or drag & drop?

**Comment by kartik-v** [comment]
You have not understood the pre-requisites then - please read the docs.

As mentioned in docs (and in other questions answered in this repo)... using drag/drop, or selectively adding files, or viewing progress, are all features available **ONLY WITH AJAX**. The plugin assumes ajax upload if you have set **uploadUrl**. If you need these functionality you must use AJAX uploads... and must provide the uploadUrl. In that case you cannot USE form submit.

If you need traditional FORM SUBMIT - you cannot use drag and drop as the data will not be available in your form submission (since you cannot manipulate a native HTML fileinput externally).

Refer #103, #135

You cannot mix both and if you try to violate the above pre-reqs... you will naturally face situations or data which are not correct OR will be inconsistent.
