### ISSUE TITLE
is there a way to import your library using webpack

### ISSUE THREAD

**Issue by szwss** [kartik-v/bootstrap-fileinput#1425]
Such reference in html:
<script src="{{ asset(mix('resources_compile/libs/bootstrap-fileinput/fileinput.js')) }}"></script>
Quoted in this file:
import 'bootstrap-fileinput'

But this does not work, the following error occurs:
$(...).fileinput is not a function

What is the problem, how should I compile it myself and import it into html?

**Comment by lacrc** [comment]
I'mma go ahead and assume you're talking about Laravel's webpack. Whether that is the case or not maybe your question is better suited to be on Stack Overflow under a "Laravel" tag, since it's not specific to this plugin.  

BUT to solve your problem I think you need to first include a require in your `resources/js/app.js` (assuming it's the default mix configuration):

`require('bootstrap-fileinput');`

Also go ahead and include (after that line) any other extensions you might need (themes or locales), I use Font Awesome icons so:

`require('bootstrap-fileinput/themes/fas/theme.min');`

Then include the css for the plugin in your app's sass main file `resources/sass/app.scss`

`@import "~bootstrap-fileinput/scss/fileinput.scss";`

Don't forget to run `npm run dev` after that to recompile your assets and you should be good to go. Hope it helps! :)

**Comment by kartik-v** [comment]
Yes as @lacrc mentioned - extend it for your use case.

**Comment by ttimot24** [comment]
How can I use this with type script?

My situation:

`var fileSelect = ($('#input-2') as any);
fileSelect.fileinput('clear');
`

```
Uncaught TypeError: fileSelect.fileinput is not a function
    success https://bluehill.hu/resources/js/app.js:3501
    fire https://bluehill.hu/resources/js/app.js:12601
    fireWith https://bluehill.hu/resources/js/app.js:12731
    done https://bluehill.hu/resources/js/app.js:18943
    callback https://bluehill.hu/resources/js/app.js:19204
    send https://bluehill.hu/resources/js/app.js:19256
    ajax https://bluehill.hu/resources/js/app.js:18837
    upload https://bluehill.hu/resources/js/app.js:3487
    submit https://bluehill.hu/resources/js/app.js:20915
    invokeWithErrorHandling https://bluehill.hu/resources/js/main.js:23029
    invoker https://bluehill.hu/resources/js/main.js:23354
    _wrapper https://bluehill.hu/resources/js/main.js:28757
```
