### ISSUE TITLE
Hovering on thumbnail weird effect

### ISSUE THREAD

**Issue by apilavakis** [kartik-v/bootstrap-fileinput#144]
I noticed this on my implementation and i thought i messed something up however i replicated it here too http://plugins.krajee.com/file-input/demo#ajax-uploads.

If you upload enough files to have two rows of thumbnails preview and try to hover on any thumbnail in the first row on top of the area from the 'not uploaded yet button' until just before the 'upload' button you will notice that the bottom row thumbnails jump to the right.

**Comment by kartik-v** [comment]
Fitting in the preview thumbnails depends on the dimensions of the file/image you are trying to select and preview in the thumbnail. It might not be same for all cases what you mention. If all your images are of consistent dimension ratio, it will behave uniformly -- however if you have images whose width is way more than height. or very oddly sized width and height. .etc.. they will shrink into the space available automatically. Hence they may be wrapping down since on hover an extra shadow is added. You can control these thumbnail sizes if needed from the `defaultPreviewSettings`.

**Comment by apilavakis** [comment]
First of all congratulations on your excellent work and your prompt response on the issues.

I will have to however disagree with what you said above. Even if you put consistent dimensions you have the same effect. I made many copies of Chrysanthemum.jpg (WIndows Sample Picture) and uploaded and i still get the same

**Comment by kartik-v** [comment]
Dimensions will be with respect to the window size  you are viewing in and the container size within which you placed the file input. The number of thumbnails in a row will be dependent on the above. The thumbnail frames will wrap down if it does not fit - which is what is happening as you hover - because of the lesser estate to fit. For smaller devices/small screen sizes it may well align in one column.

As I mentioned you need to adjust your dimensions... experiment with what works for your use case. You can adjust the dimensions from `previewSettings` for each by file type. You can also add your own CSS for your use case if you wish for advanced cases.

**Comment by kartik-v** [comment]
Dimensions will be with respect to the window size  you are viewing in and the container size within which you placed the file input. The number of thumbnails in a row will be dependent on the above. The thumbnail frames will wrap down if it does not fit - which is what is happening as you hover - because of the lesser estate to fit. For smaller devices/small screen sizes it may well align in one column.

As I mentioned you need to adjust your dimensions...  experiment with what works for your use case. 
- **Tip 1:** Increase your container width in whivh you are wrapping the widget and adjust it for your use case.
- **Tip 2:** You can adjust the dimensions from `previewSettings` for each by file type. You can also add your own CSS for your use case if you wish for advanced cases.
