### ISSUE TITLE
Prevent invalid thumb validation when `showPreview` is `false`

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/bootstrap-fileinput#1475]

**Comment by mattymatty76** [comment]
Hi,
you have updated fileinput.js just now, but the problem is not fixed.
I receive this message after updating (and before) at your last modify
in fileinput.js: TypeError:  $thumb is undefined fileinput.js:3292:21

This problem occurs when the routine fails and inside fnError being show the error message...

Thank you anyway

**Comment by mattymatty76** [comment]
Great Work!!!
Thank you very much!!!
