### ISSUE TITLE
txt file can be previewed when upload, but can not be previewed when configured in initialPreview

### ISSUE THREAD

**Issue by peter-wang-wsl** [kartik-v/bootstrap-fileinput#1511]
when `http://localhost/profile/sc/locate/2019/12/03/48f213be2a417b3e1f776df76fb96fff.txt` is configured in initialPreview, it can not be previewed;but after upload txt I can preview it.

**Comment by kartik-v** [comment]
You need to pass the TEXT FILE DATA instead of the LINK TO THE TEXT FILE when configuring initialPreview.

**Comment by peter-wang-wsl** [comment]
I knew pass the TEXT FILE DATA to initialPreview to preview. Is it possible pass link to initialPreview to preview it?

**Comment by kartik-v** [comment]
No - it is to be avoided. It is not possible to read file contents via JAVASCRIPT in a consistent way across browsers and server environments. The code can use ajax to read file content and display - but it will require the web server to support CROSS ORIGIN REQUEST and may result in CORS issues.

It is recommended to handle this at your server level... it requires just a simple code change on your server. Instead of sending TEXT FILE LINK -- in JSON you need to just send something like this in PHP

```php
'data' => file_get_contents('text_file_path_on_server')
```

**Comment by kartik-v** [comment]
If your server supports the text files to be read by ajax - then you as a developer can write the necessary javascript to get file contents by ajax and return the `initialPreview`  accordingly for text files based on your program condition.
