### ISSUE TITLE
Key from upload response is not taken to remove button

### ISSUE THREAD

**Issue by leofonic** [kartik-v/bootstrap-fileinput#1522]
## Steps to reproduce the issue

1. Upload a file
2. set "key" property in uploader response
3. delete the file (with deleteUrl set)

## Expected behavior and actual behavior
I was expecting that the key would be transmitted to the specified delete handler file for removal of the file.
Actual: key property in POST is empty

## Environment
I created a jsfiddle: http://jsfiddle.net/leofonic/rvxnywfe/18/
Some things not working but you can choose a file, upload and delete it. If the POST request to delete.php is inspected with browser console, there is the "key" parameter present but it has an empty value.
Also the data-url and data-key values in the button are present but empty.

**Comment by xantari** [comment]
Also having this same issue.

**Comment by xantari** [comment]
There is also issue, when you set caption and size info in return response within InitialPreviewConfig from server response, it doesn't actually apply it to the result... Going back to pre-5.X version to see if it works there.

**Comment by xantari** [comment]
@leofonic I just figured it out. Seems it is bug in 5.0.8 version. Does not happen in 5.0.1 version.

**Comment by leofonic** [comment]
@xantari thanks i will try this!

**Comment by elzappo** [comment]
Hey I am facing an issue which I think is related to this problem.
I assume this issue only appears for the first file uploaded. If you upload multiple files starting with the second file the InitialPreviewConfig is applied correctly again.
This behavior can be seen on the demo page 6 (https://plugins.krajee.com/file-input-ajax-demo/6).

If I see it correctly the error appears due to line 1780 in the fileinput.js because the it checks if the data.content has a length. And because it is the first item it stores the config the wrong way. This also fits to the observation with 5.0.8 because then this line of code was modified in this way.

**Comment by kartik-v** [comment]
Related to #1518.

**Comment by kartik-v** [comment]
Resolved via latest commit.

**Comment by leofonic** [comment]
Thank you @kartik-v and @elzappo !

**Comment by shankarGdev** [comment]
Can you release this fix.
