### ISSUE TITLE
Invalid upload method

### ISSUE THREAD

**Issue by XiFYuW** [kartik-v/bootstrap-fileinput#1534]
- jQuery version: 3.4.1
- bootstrap-fileinput version: 5.0.8

- According to the document and the sample upload method, the following is used:

`$('#input-id').fileinput('upload');`

- Here's how I use it:

``` 
    <input :id="uploaderFile" type="file" multiple>
```
```
    let obj = this.$jquery('#' + this.uploaderFile) 
    // uploadAsync = false
    this.$utils.fileInput.init(obj, this.option)
```
```
    obj.on('filebatchuploadsuccess', (event, data) => {
      let resp = data.response
      // The response is correct, so there is no error in the response field
      if (resp.respCode === 2038) {
        this.$central.init(resp.respData)
        obj.fileinput('upload')
      }
    })
```

- My understanding is that executing the upload method is just like clicking the upload button, and my expectation is to ask him to upload again. However, there is no effect after executing the upload method, how can I get my expectation? #

**Comment by kartik-v** [comment]
Not clear with what you are trying. I see you are calling the `upload` method after `filebatchuploadsuccess` - note that this is of no use because the `filebatchuploadsuccess` is triggered only after all files are completely uploaded and then all the files pending in the file stack are cleared and processed. So if you are triggering upload after this - nothing is going to happen because you have no files selected from client for uploading.
