### ISSUE TITLE
How can I access the route passed in zoomData only when the zoom button is pressed?

### ISSUE THREAD

**Issue by rviniciussouza** [kartik-v/bootstrap-fileinput#1590]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Expected behavior and actual behavior

Currently the route passed in the zoomData attribute inside initialPreviewConfig is triggered whenever the widget is loaded. However the behavior I expected is that this route would be triggered only when the zoom action was called.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [x] Mobile

Libraries

- jQuery version: 3.5.1
- bootstrap-fileinput version: 5.0.9

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
This is an intended and expected behavior - the zoom data is cached by the plugin on load and generates the markup for zoom on every refresh of initialPreview.

If you want a different data to be shown based on your other dynamic logic - you can disable the default zoom button via [`fileActionSettings.showZoom`](https://plugins.krajee.com/file-input/plugin-options#otherActionButtons) property and add your own custom button via [`otherActionButtons`](https://plugins.krajee.com/file-input/plugin-options#otherActionButtons) and write your logic to show your dynamic data in a modal.
