### ISSUE TITLE
a detailed preview appears in front modal form

### ISSUE THREAD

**Issue by atmanegara** [kartik-v/bootstrap-fileinput#1598]
I have 2 buttons, to access the modal form,
the first button on the modal form appears normal, the second button on the form becomes like the following picture
![image](https://user-images.githubusercontent.com/9096711/86508062-9e6dbc00-be0f-11ea-8e32-7673735abb1e.png)

**Comment by kartik-v** [comment]
Its a programming issue at your end and Bootstrap 4.x modal limitation that - you need to manage it correctly. Bootstrap CSS framework does not recommend using more than one modal dialog rendered on the same page. Since the plugin already uses its own modal dialog  for zoom preview - it will conflict with your own modal dialog. You may need to check bootstrap community to address how you can use more than one modal dialog.
