### ISSUE TITLE
Detailed preview for plain context content is empty

### ISSUE THREAD

**Issue by kikonen** [kartik-v/bootstrap-fileinput#1632]
Not sure why, but while plain text content is shown in preview, when opening modal details preview dialog, it's not shown in this modal dialog.

**Comment by kartik-v** [comment]
Not sure can reproduce your use case. Can you share a JS Fiddle to understand and reproduce your issue?

You can cross check on the demo pages as well and compare if you have a wrong code or config at your end.

**Comment by crestAT** [comment]
Hello, I'm using the latest release (v5.1.2) and have the same problem with plain text (and also html) content in the modal dialog. Furthermore in the thumbnail preview there is not the text content but the markup file path and name from initialPreview definition, eg: **http://server_ip/file_path/SampleLoremIsum.txt**
![image](https://user-images.githubusercontent.com/6754253/94725491-22c2d300-035c-11eb-9982-99700c93b035.png)

The initialPreviewConfig for this file:
`        (
            [caption] => SampleLoremIsum.txt
            [size] => 497
            [filetype] => text/plain
            [type] => text
            [url] => /delete_upload.php
            [key] => /file_path/SampleLoremIsum.txt
        )`

Up/downloads and file deletions are working w/o problems, only the preview is not working (preview and thumbnail views are fine with pdf, images and videos). Btw, the text preview in the modal dialog at the [demo page](https://plugins.krajee.com/file-preview-management-demo#preview-data) eg for **Initial Preview Data** or **Initial Preview Iconic** is also empty ... ?

Tried to find a reason for this behaviour in fileinput.js => `tText = '<textarea class="kv-preview-data file-preview-text" title="{caption}" readonly' + tStyle + '>' + '{data}</textarea>\n';` and asume, that the {data} definition holds the file markup instead of the file content for some reason.

Any help would be great, thanks in advance!

**Comment by kartik-v** [comment]
Ok thanks for the report. Noting a bug.

**Comment by crestAT** [comment]
Thanks a lot for the super-fast response!!!

Ah, I see, didn't recognize that the data is needed, not the link like for eg pdf files ...
Would be really great if it would be possible to provide only the link for text, html, csv, ... files similar as for other file types!

**Comment by kartik-v** [comment]
Fixed and enhanced via above commit. Check and let know.

**Comment by kartik-v** [comment]
For CSV files.. there is a browser specific issue which downloads files and opens them in Excel or your default spreadsheet app... instead of embedding them like normal Text files. Solution for such browser behavior currently is to disable preview for CSV files.

**Comment by crestAT** [comment]
Thanks a lot, will check it asap and keep you informed!

BR

**Comment by kartik-v** [comment]
You can check and test these in the [preview management demo](https://plugins.krajee.com/file-preview-management-demo)

**Comment by crestAT** [comment]
Tested the above mentioned fixes, they are working like a charm!

Thanks a lot for this awesome plugin!
