### ISSUE TITLE
V5.1.4 failure of filesuccessremove event

### ISSUE THREAD

**Issue by ananxier** [kartik-v/bootstrap-fileinput#1679]
V5.1.4 failure of filesuccessremove event

**Comment by kartik-v** [comment]
This cannot be reproduced in v5.1.4. Suggest to upgrade and in case you have a scenario where you can reproduce - please share a JS Fiddle and will reopen.

**Comment by anandphulwani** [comment]
I have reproduced this problem, i cannot set a `uploadUrl` since it is blocked by CORS, 
and hence i cannot duplicate this issue on codepen, jsfiddle, jsbin,
but if you just copy the code on an offline development enviroment,
the behavior appears to generate failure of filesuccessremove event.

https://codepen.io/anandphulwani/pen/oNYrvWd

## Steps to reproduce the issue

1. Upload a file, wait for completion of upload and green tick for the file.
2. Delete the file, it should generate the `filesuccessremove` event, which it doesn't.

## Expected behavior and actual behavior

When I follow those steps, I see `filesuccessremove` event not being called.
I was expecting `filesuccessremove` event being called.

## Environment

Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.3.1
- bootstrap-fileinput version: 5.0.9, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.1.4, 5.1.5

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)
