### ISSUE TITLE
maxTotalFileCount not work when uploaded

### ISSUE THREAD

**Issue by cowpy** [kartik-v/bootstrap-fileinput#1701]
## Prerequisites

- [ 1] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue
maxTotalFileCount not work correctly，in the  demo https://plugins.krajee.com/file-count-validation-demo
setp:
1. delete all the three picture
2. select  and upload 4 picture
3. then i can select and upload picture one by one  with no limit
![testst111](https://user-images.githubusercontent.com/5237001/116535058-e8331000-a915-11eb-8de5-d539f3f1813b.png)

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [1 ] Google Chrome
- [ 2] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [1 ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ 1] This bug happens [on the plugin demos page](https://plugins.krajee.com/file-count-validation-demo)
- [1 ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
This is dependent on your server code and plugin config. The demo does not include the server code to update the initial preview back to the plugin config after upload. You need to just update the initial preview back after upload so that the count will be validated. Once done the maxFileCount will work fine based on the `validateInitialCount` plugin setting.

For checking a demo of how initial preview is updated after upload [check ajax demo # 4](https://plugins.krajee.com/file-input-ajax-demo/4).
