### ISSUE TITLE
how to set key in ajax upload

### ISSUE THREAD

**Issue by snowchenlei** [kartik-v/bootstrap-fileinput#1751]
With uploadurl uploads, the service side returns not {"initialPreview":[""],"initialPreviewConfig":[{...}], how to intercept and construct at the front end
I mainly need to set key to know which one was deleted when I deleted it

**Comment by kartik-v** [comment]
Many ways to do this - because you do have access to the front end view and DOM elements like the delete buttons and trap their clicks.

One recommended way to do is to use events in the fileinput plugin like the [`filebeforedelete`](https://plugins.krajee.com/file-input/plugin-events#filebeforedelete) event which is fired just before the ajax request is fired or the [`filepredelete`](https://plugins.krajee.com/file-input/plugin-events#filepredelete) event - where you can have a dummy ajax request and prevent the ajax upload to fire by returning an abort to the event.
