### ISSUE TITLE
image rotate when choose another size

### ISSUE THREAD

**Issue by arbabi2010** [kartik-v/bootstrap-fileinput#1790]
Hi , I'm using iphone and when i choose an image form gallery and select another size instead actual size , image rotate 90degree. but when i choose actual size every thing is correct .

**Comment by kartik-v** [comment]
This depends on actually the original source image and how it is stored in your device. If it has embedded exif orientation data that will be parsed to auto rotate - if it does not it will not show rotated correctly. 

For such scenarios, the plugin offers a capability since for user to rotate the images after preview since v5.2.9.
