### ISSUE TITLE
Almost done

### ISSUE THREAD

**Issue by PhantomLord72** [kartik-v/bootstrap-fileinput#1797]
Ok, now to thumbnail of the preview is automatically updates with the right content according to the mimetype of content.
File is renamed and uploaded with the updated extension.
But the text label with the file name is not updated anymore, In the previous commit it worked.

This is been enhanced and updated via Enhancement #1785. You will get the original filename without updated extension and previews should work fine .

_Originally posted by @kartik-v in https://github.com/kartik-v/bootstrap-fileinput/issues/1793#issuecomment-1161452654_

**Comment by kartik-v** [comment]
Yes that is an expected occurence as per the feature. Renaming of the original file source will not happen as expected - because duplicate file selection checks are all dependent on this and that will be compromised.

However the plugin stores the updated file name against each thumb as a data property `data-filename` which can be parsed via javascript after uploading.

**Comment by PhantomLord72** [comment]
How can I parse from jquery?

**Comment by kartik-v** [comment]
Check the docs for plugin methods. For example [getFrames method](https://plugins.krajee.com/file-input/plugin-methods#getFrames) will get you the list of all thumbnails and you can filter the successfully uploaded thumbnails -- for e.g.
```js
var $frames = $('#input').fileinput('getFrames', '.file-preview-success'); // list of success thumbnail frames

$frames,each(function() {
    var $thumb = $(this);
    console.log($thumb.data('filename')); // returns updated filename
});
```
