### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by cyrakuse** [kartik-v/bootstrap-fileinput#190]
Hi,

Thanks for this awesome plugin !
here are my 2 questions : 

1 - automatic upload when drag and drop
i've seen that it is possible in the closed issues but how can i do that ? have you an example ?

2 - how to display only the drag and drop zone ? 
I've tried to set showCaption to false but i stil have the browse button

EDIT : 
question 3 : why i have many alert() message (like when i drag a file) and how delete them ?

Thanks in advance for reply

**Comment by kartik-v** [comment]
Use this project page for only logging issues. Try to post generic help related queries on the extension or demo page to get better response.

Most of your queries are related to building your own application code or understanding similar use cases.You may try posting it on the [demo page](http://plugins.krajee.com/file-input-demo) to get responses from others.

**Comment by cyrakuse** [comment]
i think my question 3 is an issue. It's not usable in production like this.

**Comment by kartik-v** [comment]
Your issue # 3 cannot be replicated... because alerts that will be displayed by the plugin are typically only validation errors like max file count allowed for upload etc. and that depends on what you configure as a developer. 

Try it on the demo pages and let know if you are facing any issue... if you have a scenario that you feel is an issue - try to produce a link to a JS Fiddle or something to test.
