### ISSUE TITLE
Ajax Uploads with custom response .. how to ?

### ISSUE THREAD

**Issue by djangosdk** [kartik-v/bootstrap-fileinput#224]
according to docs (Sending Data (from server) ) http://plugins.krajee.com/file-input/demo#async-send
It is forcing me to send response in json format like
 ```js
{
  //error, initialPreview, initialPreviewConfig, append
  'error': 'You are not allowed to upload such a file.',
  'initialPreview': ["<img src='http://lorempixel.com/200/150/people/1'>"],
  'initialPreviewConfig': [{
    caption: "People-1.jpg",
    width: "120px",
    url: "/site/file-delete",
    key: 1
  }]
}
```
This is not generic. we cant force others to modify their server response. Sometimes we are using other api services which have their own response format. so we need a sort of callback or modifier which can return above format on upload success.

For example:

What if my response is like 
```js
{
  "success": true,
  "data": [{
    "id": 242,
    "name": "somefile.ext",
    "location": "/some/path/somefile.ext"
  }]
}
````
and if i have some option to modify response like ```onUploadSuccess``` then 
I would easily use it like 
```js
$("#input-702").fileinput({
  uploadUrl: "/file-upload-single/1",
  onUploadSuccess: function (response) {
    //consume response in any way, iterate it  etc
    //and make a new Object with valid FileInput formatted Json
    //and return it
    return {
      'error': '',
      'initialPreview': ["<img src='/some/path/somefile.ext'>"],
      'initialPreviewConfig': [{
        'caption': "somefile.ext",
        'url': "/some/path/somefile.ext",
        'key': 242
      }]
    }
  }
});
```
Please help , how can I do this, did I miss any thing in DOC ?

**Comment by kartik-v** [comment]
> This is not generic. we cant force others to modify their server response. Sometimes we are using other api services which have their own response format.

Either I am not understanding what you are trying to do... or you are trying to do something which is totally different than the plugin - or your understanding of the plugin's options are not clear. 

The ajax upload is a feature is designed within this plugin - where is the question of third party apis to this plugin - and why do other apis need to dictate the ajax response? 

Since this plugin has been designed with a clear scope in mind to upload files from the client --- all the options to upload will using plugin's various design elements to automatically be able to react based on ajax response. 

So yes to answer shortly the json response from ajax MUST STRICTLY FOLLOW THE FORMAT mentioned in docs for the plugin to work and achieve the following:

-  For automatically validating/throwing an error it requires the `error` key in the json response. 
- For automatically displaying `initialPreview` it requires `initialPreview`/ `initialPreviewConfig` in the response
NOTE:
- You can additionally do or return whatever you need from your server action to call third party apis (this is not to be confused by what the plugin needs in its upload actions)
- If you need to react on upload success or completion with your own custom methods you must look into the plugin events like `filebatchuploadsuccess`, `filebatchuploaded` or `filebatchuploadcomplete` which is already there. You must read the docs for these - no need for the `onUploadSuccess` or some methods which are already addressed with the above.

**Comment by progjonner77** [comment]
hello sir your plugin is a very good one, but When i try uploading, it keep showing me image  not fund.
help out sir

**Comment by chriswongxp** [comment]
if response contain like this "{error: 0, ...}", it means no error, but plugin show upload error, how to fix it?
