### ISSUE TITLE
Multiple Inputs in the same form

### ISSUE THREAD

**Issue by nevits8as** [kartik-v/bootstrap-fileinput#254]
Hi, i like your work :+1: 
How i can apply the scrip for multiple inputs in the same form, each one, upload diferents images. i do it repeting the scrip how many times for each input i need, but that make a long code and i like resume in one scrip if that posible. Sorry for me english but i know u can understand me :smile:

**Comment by alsemany** [comment]
Hi,
did you found any solution for this ?
I just would like to include a hidden value of TOKEN with the POST I"m using laravel 5 
I can exclude CSFR however I don't want to do this

**Comment by alsemany** [comment]
I found that option here 

'uploadExtraData' => [
            'album_id' => 20,
            'cat_id' => 'Nature'
        ],
        'maxFileCount' => 10

this may help you also passing variables with the same form input
my regards

**Comment by alsemany** [comment]
this will be like that
```
$("#inputfiles").fileinput({
    uploadUrl: "/uploading_url",
    'uploadExtraData' : {
'inputname' : 'input_data',
    },
    uploadAsync: true,
    maxFileCount: 10
});
```

**Comment by kartik-v** [comment]
If you are using AJAX upload you can JUST use one INPUT to upload multiple files, add, append, or delete on the fly etc...  instead of generating multiple inputs. Multiple upload is possible by setting MULTIPLE attribute of the fileinput. This will also work for  FORM UPLOAD (you can still set MULTIPLE attribute of the file input ) - only thing is your browser must support HTML-5 features.

Read about the [usage modes of the plugin](http://plugins.krajee.com/file-input#usage-modes) and [browser support for the features](http://plugins.krajee.com/file-input#browser-support).

**Comment by nevits8as** [comment]
I use multiple input becouse i need upload 3 images for 3 diferents div in a page php... becouse thats images are publicity and have 3 diferent position at the page

**Comment by alsemany** [comment]
I'm sorry for misunderstand, I was searching for posting another data with the ajax..
as kartik-v  said use unique ID for each input
```
<input id="input1">
<input id="input2">
<input id="input3">
<script>
$("#input1").fileinput({ uploadUrl: "/uploading_url"});
$("#input2").fileinput({ uploadUrl: "/uploading_url"});
$("#input3").fileinput({ uploadUrl: "/uploading_url"});
</script>
```

**Comment by DanielDanielDanielD** [comment]
I ran into a similar problem and my solution was to call them not by their **ID** but by their **NAME** for example:-

`$("input[name=file1]").fileinput({})`
`$("input[name=file2]").fileinput({})`

However, after finding this solution, I ran into another problem and this is an **error messages of inputs** that only works in one of them
