### ISSUE TITLE
Can't init fileinput with javascript

### ISSUE THREAD

**Issue by rkurbatov** [kartik-v/bootstrap-fileinput#255]
I can init fileinput only with data-attributes, seems it doesn't react on init object, though events are working normally.

**Comment by rkurbatov** [comment]
Javascript initialization works only if I put init script (direct or reference) at the end of the html file. And usual way like document.ready or even window.load is wrong. So can I fix it? I have all my starting scripts at the head and don't want to change this.

**Comment by rkurbatov** [comment]
Hey, answer me somebody, please. I'm working with it a couple of days.

$(document).ready(function () {
    $('#uploader').fileinput({
        'uploadUrl': '/upload',
        'showUpload': false
    });
});

This script isn't working. Neither document.ready, nor window.load.

How should I use it? And how can I change uploadUrl or extraData during script execution? All I can now is to set them on start with data-attributes or with script placed just after that fileinput.

**Comment by rkurbatov** [comment]
I've managed it to work at last disabling autoconversion of all 'type=file' elements in script. Strange behavior as for me...

**Comment by kartik-v** [comment]
Please check [docs and demos](http://plugins.krajee.com/fileinput).

- If you wish to use just data attributes and no javascript you need to add the `class = file` to your input markup
```html
<input id="input-1" class="file" type="file" data-attributes...>
```

- If you want to use javascript to initialize the plugin, then remove the `class = file` from the above markup and then initialize.

**Comment by rkurbatov** [comment]
No. It automatically init all elements with *type* = file, not *class*. And when I remove type=class, I have a broken control.

I've disabled that conversion at the end of library code. May be it's better to use class or attribute like "no-auto-init" to prevent autoconversion where I want to do it manually.

And I haven't found the way to change params after initialization. For example to change uploadExtraData I need to use special function which returns common visible object or use a closure instead of giving it to control directly.

**Comment by kartik-v** [comment]
Not sure I understand what is the markup you are creating and how you are initializing the plugin (hope you have checked the example codes closely and carefully on demos for various use cases). 
OR Not sure you understand exactly how you need to initialize.

Yes `type = file` is needed always for your input irrespective of what you want to do... since it is a fileinput you need to fallback to if javascript is disabled on the browser.

The question is about how you want to initialize? Assuming you have the assets loaded as per the [plugin usage documentation](http://plugins.krajee.com/file-input#usage) - plugin will generate the transformed file input/upload output automatically in one of the following ways.

### OPTION 1: With just data attributes 
If you just have a markup like below set on your page 
```html
<input id="file-0" class="file" type="file" multiple data-min-file-count="1">
```
NOTE: You do not need any other javascript after the above markup if you have `class=file`. 


### OPTION 2: With javascript:
If you just have a markup like below set on your page 
```html
<input id="file-1" type="file" multiple>

<script>
$(document).on('ready', function() {
    $("#file-1").fileinput({
        minFileCount: 1
    });
})
</script>
```
NOTE: The ID attribute in your markup is important and must be unique for initializing and you MUST NOT SET `class = file` if you are initializing via javascript.

**Comment by rkurbatov** [comment]
Ok. Sorry for language, but i'll try to explain. The end of fileinput.js

$(document).ready(function () {
        var $input = $('input.file[type=file]'), count = $input.attr('type') ? $input.length : 0;
        if (count > 0) {
            $input.fileinput();
        }
    });

Libraty Inits all elements with attr type=file. So when I use my script with document.ready initialization it will work *after* this autoinit. I need to comment out this piece of code to have possibility use my custom initialization in my script that starts in document.ready handler.

You initi fileinput earlier than me. I could prevent it adding my init script just after fileinput markup but I want it to be inside document.ready handler.

So possible solution is to mark fileinputs in some way to prevent their autoinit. It can't be done by removing type = file, because it breaks their appearance.

**Comment by kartik-v** [comment]
>Inits all elements with attr type=file.

No that is not correct. Check the code closely. It inits all elements with attr `type = file` and `class = file` - as I have been reiterating in the past comments.

**Comment by kartik-v** [comment]
>Inits all elements with attr type=file.

No that is not correct. Check the code again closely. Plugin inits elements with combination of:
-  attr `type = "file"` 
and 
- `class = "file"`
as I have been reiterating in the past comments.

Try removing the `class = file` from your input markup - it will not initialize automatically.

**Comment by rkurbatov** [comment]
Sorry, mu fault. I thought I've tried removing both type and class and it didn't work.

**Comment by hex6ng** [comment]
This behavior is incredibly counter intuitive.  Had me pulling out my hairs for days.

**Comment by saadabdurrazaq** [comment]
bootstrap-fileinput is really suck...
