### ISSUE TITLE
upload form data order

### ISSUE THREAD

**Issue by rkurbatov** [kartik-v/bootstrap-fileinput#265]
I've reedited my comment to be more coherent.

I have a problem with post data uploading order. You create ajax request with formdata API. So request consists of files and THEN extradata fields. This request is parsed on server side field by field. So when multer (or busboy, which lies underneath) meets file - it processes file. If it meets field - it adds that field to req.body. But if i need that fields during file processing, I can't use them until all files are proceed. So I need to save all of my files, then receive all extraData and only then do something with all that stuff. Too unhandy.

**Comment by rkurbatov** [comment]
I can use url for parameters passing, but it can be done only during init. If I need, for example, send directory name that defined in user session, i can't do it. I've tried to solve this with dirty hack - i created the function that prepends formdata with given values. But it's too dirty. It would be better to give standart way of doing so. So there are two issues:

1) changing params after init (at least some of them, like uploadUrl)
2) order of formdata fields. Now extraData (which I can change from script in very innatural way) are passed AFTER files that causes problems on server side as in my case.

**Comment by kartik-v** [comment]
Not clearly able to understand where your problem is... but if I try to make out... most of your validation and processing what you are mentioning are on the server code side.

How you design each file to link to your extra data --- should be part of your application design. It should be no different than how you read a set of fields submitted via form to a server.

You must note that file uploads are always managed separately in web applications and also read separately via server code (for example $_FILES in PHP instead of $_POST for all other form data). You need to hence work with designing your app to arrange inputs and data accordingly based on your file upload sequence.

You can also play around with multiple vs single uploads if you want each file to be specific to a particular data... For example use single uploads only and treat all your extra data pertinent to the single file upload (and maybe loop this for multiple scenario). But it all depends on how you want to design your app?
