### ISSUE TITLE
Remove error message after file is removed

### ISSUE THREAD

**Issue by thejahweh** [kartik-v/bootstrap-fileinput#281]
The error messages stay there for ever.

Is it also possible to set an upload error for a specific file? If I return an error with JSON every file is marked red.

**Comment by kartik-v** [comment]
Error messages will stay until you clear the input OR you re-run the upload with correct validation.

Read the [ajax uploads section](http://plugins.krajee.com/file-input#ajax-uploads) again carefully and entirely where your queries are addressed (read how you send the data back from the server with errors depending on if you are using async or sync).

- If you use asynchronous upload then automatically you get the error message for each and every file - because it fires a parallel ajax request for each and every file - based on the `error` string you send.
- If you use synchronous upload - there's only one ajax request... so in addition to `error`, you need to set `errorKeys` as an array of the file indexes that faced the error.

**Comment by thejahweh** [comment]
1 Problem
I use async and return an error, the problem is, that the `span.file-input` gets the class `has-error`, which does affect every underlining input field.

2 Problem
The file with the error can be removed with the remove button, but why does the error which is related to the file not disappear too?
