### ISSUE TITLE
The fileinput init function can't work in $(document).ready(function() {});

### ISSUE THREAD

**Issue by FunnyAlex** [kartik-v/bootstrap-fileinput#291]
I put the script in $(document).ready(function() {.....});, like:
<script>
    $(document).ready(function() {
	$("#test-upload").fileinput({
            'showPreview' : false,
            'allowedFileExtensions' : ['jpg', 'png','gif'],
	    'elErrorContainer': '#errorBlock',
	    'overwriteInitial': true,
            'initialCaption': "The Moon and the Earth",
        });
    });
</script>

But it can't work.

If I put the script out of the $(document).ready(function() {.....});, it can work.

My bootstrap-fileinput is 4.2.0, bootstrap is 3.0.2. Jquery is 1.10.2. Chrome and firefox have the same issue.

**Comment by kartik-v** [comment]
Not sure of what your issue is... because it should work on document ready without any issues and is normally the recommended way.

You can check that it works fine on the demo pages by cross checking the generated HTML source on the [demo page](view-source:http://plugins.krajee.com/file-input/demo).
