### ISSUE TITLE
Limit upload single file and only one file in preview file section

### ISSUE THREAD

**Issue by ducnguyenhuy** [kartik-v/bootstrap-fileinput#409]
What's options for followings:
- Only allow preview one file at time
- Only allow upload one file at time

My issue: When I click on browse button and select one file (file A), the upload is auto started (my setting), then I click on Browse button again and select other file (file B), I see two files uploaded and they're in file preview section. I'd like file B should replace file A. How to solve this issue?

Thanks.

**Comment by kartik-v** [comment]
Since you are auto uploading to server - the client plugin will not know about what you want to do next. For your use case you typically can do one of the following:
1. on the client side you can try disabling the fileinput after file is uploaded (e.g. you can use the [`disable` method](http://plugins.krajee.com/file-input#method-disable) of the plugin.

2. or alternatively you can check this in your your server code (e.g. php) and trap the duplicate upload and return an error 

For other cases you can set the [autoReplace](http://plugins.krajee.com/file-input#option-autoreplace) property with `maxFileCount` set to `1` to ensure plugin overwrites files selected with 1.

**Comment by juliovedovatto** [comment]
I'm able to made using this code:

```javascript
element.on('fileloaded', function(){
	if ($(this).closest('.file-input').find('.file-preview-frame').size() > 1)
		$(this).closest('.file-input').find('.file-preview-frame:eq(0) .kv-file-remove').click();
});
```

Not the most elegant way, but it works for what I want to accomplish :)

**Comment by peter-wang-wsl** [comment]
@kartik-v  I use below code, but can not disable browser button
```
.on('fileuploaded', function(event, data, previewId, index) {
    $('#executionDoc').fileinput('disable');
})
```

**Comment by kartik-v** [comment]
Check after #1510 fix.

**Comment by HubQin** [comment]
> I'm able to made using this code:
> 
> ```js
> element.on('fileloaded', function(){
>     if ($(this).closest('.file-input').find('.file-preview-frame').size() > 1)
>         $(this).closest('.file-input').find('.file-preview-frame:eq(0) .kv-file-remove').click();
> });
> ```
> 
> Not the most elegant way, but it works for what I want to accomplish :)

Thanks for your resolution, I made some adjustment to make it work:
```
// remove the first one preview
if ($(this).closest('.file-input').find('.kv-preview-thumb').length > 1) {
        $(this).closest('.file-input').find('.kv-preview-thumb').eq(0).remove();
 }
```
