### ISSUE TITLE
CSS classes not defined?

### ISSUE THREAD

**Issue by DigitalFusionTom** [kartik-v/bootstrap-fileinput#463]
Hi,

Am I missing something, or are some of the classes not defined?  In the fileInput.js file there are references to classes that are prefixed with "kv-".  For example: 

``` HTML
<div class="kv-upload-progress hide">
<div class="kv-fileinput-error">
<span class="glyphicon glyphicon-file kv-caption-icon">
```

However, in the CSS file, there is no definition for these classes?  So, for example, when an image that is too large is selected, the error message isnt displayed?

![coverimageerror](https://cloud.githubusercontent.com/assets/14911835/10225459/93792920-6828-11e5-9014-144d59e39726.JPG)

**Comment by DigitalFusionTom** [comment]
Hello?  Anyone? 

Am I missing files or something?  I downloaded the latest version, and the CSS classes referenced in fileinput.js are not defined in fileinput.css.  Where are the CSS classes that start with "kv-" defined?  Are these js-only classes?

**Comment by DigitalFusionTom** [comment]
I checked, they are the JS classes, Im used to using IDs for this, not classes.  I had to add  style="white-space:normal !important" to the input-group-btn class in order to see the errors.  Im guessing with all the plugins we have, there is a css conflict somewhere

**Comment by kartik-v** [comment]
These are JS classes and have nothing to do with the plugin styles.

There is a reason for using CSS classes for certain internal selectors and not ID attribute - because this allows for multiple file input widgets on the same page (having the same ID on same page will cause breaks in functionality).

For styling - yes you would need to check your internal CSS and see if they are conflicting and set classes and container settings using the various plugin properties
