### ISSUE TITLE
A way to know file list and delete all files when clear or autoremove a file

### ISSUE THREAD

**Issue by RedFoxy** [kartik-v/bootstrap-fileinput#472]
Hi!
it'll be useful if there is a way to get files list of actve files (uploaded or pre-charged at page load), it will useful for do some works, like, I need to delete old uploaded file every time you upload a new one, to do it I'm using a "patch", like I delete all files in the upload directory but I don't like it, I prefer to get files list from fileinput ad send delete, one by one or in array, by ajax.

another trouble with your plugin is about autoupload but there isn't an autodelte! I upload by ajax and every time my users upload a file old one must be deleted (and preview must be removed but your plugin don't remove it, overwriteInitial: true) than I must use filepreajax event and when I push "clear" button it don't send delete to the server, I must use fileclear event to delete old files.

**Comment by kartik-v** [comment]
Deleting files or understanding list of files on server is to be handled via server code as there is no way for the javascript plugin to know about this. 

Plugin can send the list of files which is currently being uploaded and you can get the list of files currently being uploaded (either via FORM POST or in your ajax action depending on your usage)

The server (or ajax) code that processes any upload on server must be able to parse and read the files previously uploaded and manipulate.

Plugin offers some options to send additional data to handle such use cases. If you need custom data or actions for each thumbnail (e.g. a delete checkbox for each thumbnail) - then you can send this information through 

- `uploadExtraData` for new files 
- `initialPreviewConfig.extra` or `deleteExtraData` for server uploaded files 

You can also configure the above properties as a callback function so that they send data dynamically to your server,

Check an example in [ajax upload example # 7](http://plugins.krajee.com/file-input-ajax-demo/7) for details.

**Comment by andrewblake1** [comment]
@RedFoxy 

There is a way to get list of files. However you pass the info you want i.e. I use key within initialpreviewConfig. Note I wasn't intending posting any of this as real, solution, I too had noticed the same but have solved (until find a way a breaks anyway) with the event handlers. Similarly I think though would be great if there was an option to achieve your suggestion without this. Pretty sure @kartik-v doesn't like hacky solutions like this being needed so I am sure there will be a better solution offered at some stage :)

Assuming you are doing this within an event 
```
function filecleared(event) {
    var $this = $(event.currentTarget);
    var fileinput = $this.data('krajee-fileinput');
    if (fileinput = window[fileinput]) {
        if (fileinput.initialPreviewConfig.length) {
            // add hidden delete records for all in the initial preview
            $.each(fileinput.initialPreviewConfig, function() {
                filedeleted(event, this.key);
            });
        }
    }
}
```
note that filedeleted is my handler for delete button hit, point really is that you can access the initPreviewConfig and loop to get list of files - however you have used initialPreviewConfig i.e. I use key for filename you, might use initialPreviewConfig.extra.

Incidentally this bit should solve the last bit of your issue i.e. when the init preview files are removed from the preview area - triggered by an upload:
```
/**
 * Event handler called when a file is loaded into the preview area.
 *
 * This should only be enabled when autoreplace is true hence causing preview files that are automatically replaced
 * to be added to our list of hidden elements indicating deletes.
 *
 * @param event
 */
function fileloaded(event) {
    filecleared(event);
}
```

and below is my filedeleted event handler though you would need to make use of uploadExtraData (as in ajax mode), when sending (I am currently still in form submit mode for now). Currently I add hidden element carrying the filename in the value. You could potentially use this and then extract the files from the hidden elements in filepreajax or just keep the files to be deleted in a variable perhaps? I am not sure yet how robust this bit is - scanning for "init_0" was a guess without looking at the source.
```
/**
 * Event handler for when the delete file operation is finished here in client. This is a toggler, hence if the file
 * is already deleted, then assumes we are undeleting i.e. removing the hidden element indicating a file delete
 * @param event
 * @param key   Passed in as the key from getExistingFiles in FileActiveRecordTrait, this is the file name
 */
function filedeleted(event, key) {
    var name = event.currentTarget.name.replace(/[\[\]']+/g,''),
        hiddenDelete = $('[name="delete[' + name + '][]"]');

    // if the first initial image is showing
    if ($('[data-file_index="init_0"]').length) {
        // remove hidden delete input
        hiddenDelete.remove();
    } else {
        // add hidden element to indicate delete (only if it doesn't already exist)
        if (hiddenDelete.length == 0) {
            $('<input>').attr({
                type: 'hidden',
                value: key,
                // name is set to the attribute name within the model
                name: 'delete[' + name + '][]'
            }).insertAfter(event.currentTarget);
        }
    }
}
```
This isn't well tested yet but works for me for now. Hope it helps in the interim.

**Comment by kalpeshparakh** [comment]
Hi Kartik,

Thanks for such a wonderful plugin...

I am trying to upload a list of documents, using your plugin. But the only issue with it is that the plugin gives multiple calls to my server code rather than sending the list of files in one go.

i.e. suppose i am uploading 5 files at a time and click on upload, your javascript gives ajax call to my server code 5 times. whereas i need a way so that i can send all the 5 files at once to my server function. so that the server function is called only once. the server function is accepting a list of files rather than a single file.

Please comment.

**Comment by andrewblake1** [comment]
@kalpeshparakh Haven't been doing coding around this widget for a while so @kartik-v will correct if wrong, but if it helps, pretty sure by memory that mine is uploading via ajax, multiple files in a single call like you want. Suspect kartik will steer you towards a close reading of the docs for the plugin and the options.

Without looking back thru the docs myself to refresh, and looking at my own settings am guessing you should first look into the uploadAsync option and ensure you have it set to false - NB it is true by default which would cause what you have described.

Can't 100% recall but I seem to remember do a bit more coding around this to get the exact smooth operation that I decided to work consistently with my other code, but it all does work and is an awesome plugin.

**Comment by kartik-v** [comment]
@kalpeshparakh and rest... yes I would always recommend to read the documentation before raising an issue OR trying out your coding because your programming use case is exactly addressed there.

Read the [ajax uploads section of the documentation](http://plugins.krajee.com/file-input#ajax-uploads) of the documentation. Read about Synchronous and Asynchronous uploads. 

For Asynchronous upload (when `uploadAsync` is `true` and is the default)... parallel ajax calls will be fired for each and every file selected... and each file is sent separately with every request to server.

For Synchronous upload (when `uploadAsync` is `false`)... only one ajax call will be fired... and all files sent as one batch array to server.

**Comment by kalpeshparakh** [comment]
Thanks alot @kartik-v and @andrewblake1 for a quick response,  i will try this.

**Comment by karthickraja087** [comment]
Hi Kartik-v, 
Thanks to your Plugins it help us lot.
Can you tell me, I want sent data of file after upload, it works fine.
But when i delete one file after uploaded, if i submit no data sent.
Also if i drop my file into it, and submit no data sent.
if Any one know it please help me.
