### ISSUE TITLE
Load script in Zf2

### ISSUE THREAD

**Issue by Paul75** [kartik-v/bootstrap-fileinput#475]
Hello,

The script is installed by composer.

When in layout I must declare the js and css ?

Thanks

**Comment by kartik-v** [comment]
Not sure what the issue is. You may want to post framework specific configuration outside this OR try using the plugin [discussions and comments section](http://plugins.krajee.com/file-input#comments) to get help.

Refer [installation and configuration steps for plugin here](http://plugins.krajee.com/file-input#installation).

**Comment by Paul75** [comment]
I use Zend Framework 2.....
