### ISSUE TITLE
Problem with IE10

### ISSUE THREAD

**Issue by klnjmm** [kartik-v/bootstrap-fileinput#477]
Hello,

I have a problem with IE10 and there is the same bug on your website.
In the "Advanced Example 3" demo, a single click on the browse button doesn't open the "Choose file to upload" window. I have to either click on the right on the block button or double click on it.
This problem is not present in Firefox or Chrome.

Is it possible to fix this bug ?

See gif file attached : 
- First click : no effect
- Click on the right on the button : dialog open
- Double click : dialog open

![bootstrap-file-input-ie10](https://cloud.githubusercontent.com/assets/15214050/10608464/7071ee6e-773f-11e5-9ea8-a40715e1914a.gif)

**Comment by kartik-v** [comment]
I am not sure why - but its been a real pain to do specific stuff separately for IE versions each time. Will need to check when I get time if there is any CSS fix for this.

**Comment by klnjmm** [comment]
Ok thanks. Hope you can find a solution easily.

**Comment by kartik-v** [comment]
Resolved via specific fix for IE10.

**Comment by klnjmm** [comment]
Hi,

Thanks for your reactivity. But I always have the problem : now, only double-clic work. One click on the button doesn't open the dialog.

**Comment by kevin2531** [comment]
I have the same issue

**Comment by alexlomba87** [comment]
I solved this problem by using:
`<script>
    // - Correction for IE double click instead of single click 
    // - issue happening with 
    if (navigator.userAgent.indexOf("MSIE 10") > 0) {
        $("#input-2").bind('mousedown', function (event) {
            $(this).trigger('click')
        });
    }
</script>`

at the bottom of the HTML document where I'm using bootstrap-fileinput.
Just change "#input-2" to the ID of your button.
You can modify "MSIE 10" to a general "MSIE" so it works also for IE9 and 8.

This solved the double click instead of single click issue for IE10 for me.
Thanks to @nagyt234 for the proposed solution in tors/jquery-fileupload-rails.
[https://github.com/tors/jquery-fileupload-rails/issues/33#issuecomment-23645303](url)
