### ISSUE TITLE
File not posting when rendering widget on modal

### ISSUE THREAD

**Issue by box2424** [kartik-v/bootstrap-fileinput#487]
I've searched around a bit and can't solve this problem.  The widget is working fine when I have it render in a regular view; however, when I use that same view file as a partial view in a bootstrap modal dialogue and post the form, the post is always null for the upload input while the rest of the form elements post correctly.  Was wondering if you have run into this issue and/or could think of possible problems with the implementation. 
Thank you.

**Comment by kartik-v** [comment]
You need to check your code and ensure that the plugin is reinitialized after every ajax completion to run the JS scripts in your partial view. If you are using Yii use the renderAjax method instead of renderPartial.

If you need newbie help OR have generic programming queries or need programming tips - there is a new forum created for this. Please [ask a question on the forum here](http://webtips.krajee.com/questions).
