### ISSUE TITLE
Preview of many images does kill the browser

### ISSUE THREAD

**Issue by thejahweh** [kartik-v/bootstrap-fileinput#500]
There is a problem when many images are uploaded it loads the previews fully in the browser memory and kills the browser. Is it possible to make thumbs on JS-side and do not load the whole image in the memory?

**Comment by kartik-v** [comment]
Images are needed to be loaded in browser memory for various functionality reasons and it depends on the developer to control it currently. The needs for images being read on client are for:

- displaying in preview and performing activities after image is loaded in preview
- validating image dimensions and properties
- performing image related manipulations (e.g. resizing images) and triggering events after image is loaded

You may need to plan your application design in such a way that you do not allow infinite or a large number of images to be previewed on the browser 

- for example set `maxFileCount = 5` to allow only  5 images at a time for upload
- and/or set maximum size of image to be uploaded (so that it disallows such image to be previewed)
- and/or you may disable preview by setting `showPreview` to `false` which will entirely eliminate reading each file in memory.

**Comment by thejahweh** [comment]
Thanks for your quick reply.

I have to allow upload 200 pictures at once. This means it does work if I just disable the `showPreview` function, but then the user is not anymore able to delete a picture afterwards. So the `showPreview` option has to be on.

What I tried is to set the `allowedPreviewTypes` to nothing, which does then just shows a placeholder. Thats what I wanted, after the upload it shows the preview which is great. But is it possible to show a thumbnail before it gets uploaded and just resize it to 100x100 or something like that, just to not consume too much memory?

My current problem is, that I have to give the image resizing to some workers on the server-side and the thumbs not always ready when the upload is finished so it shows only a 404-image-placeholder.

**Comment by kartik-v** [comment]
Yes it all is upto the developer to control it. Since whatever you need is dependent on each client machine and browser specs to be able to handle and process the size and scale of data.

If you need that large number of images without any size restrictions... one option is to set `allowedPreviewTypes` and configure them to not load the image thumbnails as described in the [demo here](http://plugins.krajee.com/file-preview-icons-demo).

However showing a small or a big thumbnail will still require reading the image on the client. You can resize images on client to smaller thumbnails using the [image management functionality as shown here](http://plugins.krajee.com/file-image-management-demo). However, it still requires the HTML 5 canvas to read the whole image and resize it on the client. This feature only helps you save your server bandwidth and allows smaller files to be stored. However if your source image is large - it will still need to be read on client browser to do any image manipulation or reading or display on client.
