### ISSUE TITLE
Multiple files

### ISSUE THREAD

**Issue by Cannonb4ll** [kartik-v/bootstrap-fileinput#502]
I am currently using this plugin, its really nice and good. Only problem I am experiencing is that it does not allow me to upload multiple files, it just replaces the previous file inside the container preview.

I have multiple inside my file HTML tag, and the name contains square brackets ( [ ] ), what am I doing wrong?

**Comment by kartik-v** [comment]
Read this [section of the documentation on usage modes of the plugin](http://plugins.krajee.com/file-input#usage-modes).

**Comment by Cannonb4ll** [comment]
I have, thoroughly actually, I cannot seem to get it working properly, can you see something wrong with this code?

{!! Form::file('images[]', ['class' => 'form-control', 'id' => 'file-upload', 'placeholder' => 'Afbeeldingen', 'type' => 'file', 'multiple' => 'multiple', 'data-show-upload' => 'false', 'data-show-caption' => 'true']) !!}

$('#file-upload').fileinput({
   minFileCount: 1,
   maxFileCount: 10,
});

**Comment by kartik-v** [comment]
You are using a normal form based submission without `uploadUrl` (ajax).

If you read docs again carefully - the normal form based submission mode does not support many features that is supported by ajax (due to limitation of the HTML native file input being modified via javascript).

Normal form based submission using NATIVE file input does not allow you to append or delete files individually on client before upload. Read about the comparison of modes on the link I sent above.

An option is for you to use ajax mode where you can append files but you need to set an `uploadUrl`  to a server action that will receive and process the files and extra data for upload ... here you can append files etc..

**Comment by Alexander--** [comment]
@kartik-v 

Please reconsider this issue: this plugin can read old value to Blob (via FileReader) and remember it across new file selections
