### ISSUE TITLE
A way to sort the images

### ISSUE THREAD

**Issue by Cannonb4ll** [kartik-v/bootstrap-fileinput#503]
I would like to see a way to sort images in the preview content, and that the uploader takes in place which sort order it is from left to right. (You would get the right sorting order in the request according to the sorting you've done in the plugin)

**Comment by kartik-v** [comment]
Not in immediate focus because there are many such in the wish list like drag and drop and reorder - all of these will actually bloat the plugin and needs exhaustive testing. These can be done externally via other JS plugins by tapping into this plugin's events and methods.

But feel free to submit a PR for this enhancement so that it can be accelerated. Am closing this currently - but can reopen it if you have a suggestion to hasten this.

**Comment by mohammadsj** [comment]
Images can be re-order after uploading but not when we add them.By that mean we can't re-order images unless we upload them

**Comment by kartik-v** [comment]
Yes that is the scope of the sortable feature in the plugin. You can currently only sort uploaded files. The handling of sort for non uploaded files is not trivial and not in scope of the plugin as of now unless you wish to submit a PR.
