### ISSUE TITLE
Parallel ajax uploads limit

### ISSUE THREAD

**Issue by danielearning** [kartik-v/bootstrap-fileinput#518]
- Can I limit the number of parallel uploads? By parallel I mean until server acknowledges the upload of a single file. I usually have up to 5-6 concurrent/unconfirmed by server uploads.
- I want to enable thousands (or unlimited) uploads. But the blobs used in the image previews kill my browser after a few hundreds. I tried turning off showPreviews on-the-fly, after 20 preview images, in the fileImageLoaded event, but the input resets and it no longer shows how many files are to be uploaded. For now, I am substituting the blobs by placeholder images, but I'd rather use the non-ajax upload for that. What approach would you recommend?

**Comment by kartik-v** [comment]
This is not typically related to the plugin (because designing a complex ajax queuing process is not the objective for the plugin). So  the solution could be in your app design. Your application design needs careful programming thought. 

On one hand you know you will be limited by CLIENT specifications and CLIENT BROWSER capability and memory to handle FILE blobs beyond a certain number and size. You have to think about other design parameters like user experience and design your app accordingly.

Either you limit the number of files, sizes and preview for upload - to give the best optimal performance

OR

You need to implement a right queuing mechanism on your app. One way to do that would be to have multiple file inputs that would be used to select files and queue the uploads one by one.
