### ISSUE TITLE
loading files to bootstrap fileinput

### ISSUE THREAD

**Issue by kelumKP** [kartik-v/bootstrap-fileinput#522]
This is HTML file location for bootstrap input

   @ViewBag.Product_ID
   <input id="attachments" type="file" multiple="true" class="file" data-preview-file-type="text">

This is the location relevant files located

~/Content/Essential_Folder/attachments/Product_ID

this Product_ID folder can be vary. but its define once page load ,I'm getting that Product_ID folder name using ViewBag

also files in that Product_ID folder can be few or single or none, I just want to load them all

here the approaches I tried

Approach 1 :

   $("#attachments").fileinput({

    type: 'POST',
    cache: true,
    uploadUrl: '@Url.Action("UploadFiles", "Home")', // server upload action
    overwriteInitial: false,
    uploadExtraData: { foldertype: "attachments_EN" },
    minFileCount: 1,
    maxFileCount: 5,
    initialPreview: [
    "<img style='height:160px' src='~/Content/Essential_Folder/attachments'+ViewBag.Product_ID+>",

Approach 2 :

    $("#attachments").fileinput({

    type: 'POST',
    cache: true,
    uploadUrl: '@Url.Action("UploadFiles", "Home")', // server upload action
    overwriteInitial: false,
    uploadExtraData: { foldertype: "attachments_EN" },
    minFileCount: 1,
    maxFileCount: 5,
    initialPreview: [
    "<img style='height:160px' src='https/localhost/Essential_Folder/attachments'+ViewBag.Product_ID+>",

**Comment by kartik-v** [comment]
Your issue is not clear. You may read and go through [plugin docs](http://plugins.krajee.com/file-input) and [plugin demo examples]((http://plugins.krajee.com/file-input/demo) to understand.

If you need newbie help OR have generic programming queries or need programming tips - there is a new forum created for this. Please [ask a question on the forum here](http://webtips.krajee.com/questions). Use this repo for raising plugin issues, bugs or enhancements.

**Comment by kelumKP** [comment]
can you just look at this Stakoverflow question please , let me do if this possible to do 

http://stackoverflow.com/questions/34153755/loading-files-from-folder-to-bootstrap-fileinput

**Comment by kelumKP** [comment]
@kartik-v  can you let me know is this possible to do
