### ISSUE TITLE
Archives showing up as text

### ISSUE THREAD

**Issue by TabLand** [kartik-v/bootstrap-fileinput#544]
I've experimented with the plugin, and uploaded a .zip file, a .7z file and a .rar, and all preview as text showing Object content (object class="file-object").
Archives should be detected by file extension, or by mime type and not displayed as text as it appears as gibberish.

**Comment by kartik-v** [comment]
Read the docs and study the [allowedPreviewTypes](http://plugins.krajee.com/file-input#option-allowedpreviewtypes) property.

If `allowedPreviewTypes` not set, it defaults to `['image', 'html', 'text', 'video', 'audio', 'flash', 'object']` and hence all objects are attempted to be rendered by the browser. 

You can remove the `object` from above and set `allowedPreviewTypes` to `['image', 'html', 'text', 'video', 'audio', 'flash']` so that objects are not read and previewed.
