### ISSUE TITLE
how to get post data in node.js server? req.body is empty

### ISSUE THREAD

**Issue by lomtest** [kartik-v/bootstrap-fileinput#552]

**Comment by kartik-v** [comment]
You are wrongly reading post data. Note that handling FILE INPUT is different than handling plain text data from other form inputs. You must read `FILES` instead of `POST`. Read your server code documentation on how you handle FILES to be uploaded via a native FILE INPUT and follow the same process.

**Comment by kartik-v** [comment]
You are wrongly reading post data. Note that handling FILE INPUT is different than handling plain text data from other form inputs. You must read `FILES` instead of `POST`. Read your server code documentation on how you handle FILES to be uploaded via a native FILE INPUT and follow the same process.

You can post such queries in the [Q & A Forum](http://webtips.krajee.com/questions) in future.
