### ISSUE TITLE
Upload button shows when showUpload:false

### ISSUE THREAD

**Issue by travy** [kartik-v/bootstrap-fileinput#566]
I've noticed an issue where file upload thumbnails will still have the upload button on them when the showUpload setting is set to false.  This is with version 4.3.0

Code Snippet:

$('#input-1').fileinput({
                uploadUrl:"/file-upload-batch/2",
                imageWidth:250,
                imageHeight:250,
                showUpload:false
            });

Output:

![when off](https://cloud.githubusercontent.com/assets/4945102/12994592/c868d65a-d0ef-11e5-820c-ac56ba68831e.PNG)

**Comment by kartik-v** [comment]
You may want to [read the documentation](http://plugins.krajee.com/file-input) thoroughly.

That is expected... because `showUpload` property is only applicable for the large upload button.

Thumbnail specific file actions are controlled via `fileActionSettings`. Read the [docs for `fileActionSettings`](http://plugins.krajee.com/file-input#option-fileactionsettings). You can set the following for your use case to hide the upload button

```js
fileActionSettings = {
    uploadClass: 'hide'
}
```

You may post queries on general programming help in [this new Q & A forum](http://webtips.krajee.com/questions) in future.
