### ISSUE TITLE
Display incorrectly in other language (for example:Chinese)

### ISSUE THREAD

**Issue by JKChen** [kartik-v/bootstrap-fileinput#58]
This is an awesome plugin and really helps me a lot.
I found that it display incorrectly in other language (for example:Chinese) , not only the preview part,but also the caption,title...
how can i fix it?ths very much~

**Comment by harrisongu** [comment]
I believe the UTF-8 encode support Chinese chars, but still looks like display chinese file name  incorrectly on this plugin, could you please help to fix this issue? Thanks.

example:
I will upload this file,
![5031577d-f3f0-4594-b8e7-70f054d2c28b](https://cloud.githubusercontent.com/assets/4023273/6938228/64e86298-d894-11e4-9332-ad494840831f.png)

but the result is:
![8747f44d-f5bd-4736-bb45-0d254df6aa99](https://cloud.githubusercontent.com/assets/4023273/6938249/895f029e-d894-11e4-83a0-e186a09c53e9.png)

lost all chinese chars.

**Comment by kartik-v** [comment]
The UTF-8 encoding is only for previewing text files not for the file names in files.

What you are mentioning is the file name which is displayed in the file caption? Note that the plugin uses a slug routine to replace all special characters so that the caption can be properly parsed by javascript for and properly displayed as a valid HTML.

You can override this by using your own callback function [using the slugCallback property](http://plugins.krajee.com/file-input#option-slugcallback)

**Comment by kartik-v** [comment]
The UTF-8 encoding is only for previewing text files not for the names of files.

What you are mentioning is the file name which is displayed in the file caption? Note that the plugin uses a slug routine to replace all special characters so that the caption can be properly parsed by javascript and also properly displayed as a valid HTML.

You can override this by using your own callback function for generating the file caption [using the slugCallback property](http://plugins.krajee.com/file-input#option-slugcallback).

Refer a related discussion #64.

**Comment by harrisongu** [comment]
Thanks @kartik-v, 

I've used the slugCallback property to fixed this issue.

```
        elErrorContainer: null,
        slugCallback: function(filename) {return filename.replace(/^.*[\\\/]/, '');},
        dropZoneEnabled: true,
```
