### ISSUE TITLE
Uncaught TypeError: objUrl.createObjectURL is not a function

### ISSUE THREAD

**Issue by dmironov0** [kartik-v/bootstrap-fileinput#601]
Hi. I just can't understand what is going on with this problem.
One day, the plugin worked perfectly, then I just clicked again and this happened.

I tried in all browsers, and the same.

The lines that are breaking are these:
```
var node = ctr + i, previewId = previewInitId + "-" + node, isText, file = files[i],
                    caption = self.slug(file.name), fileSize = (file.size || 0) / 1000, checkFile, fileExtExpr = '',
                    previewData = objUrl.createObjectURL(file), fileCount = 0, j, msg, typ, chk,
                    fileTypes = self.allowedFileTypes, strTypes = isEmpty(fileTypes) ? '' : fileTypes.join(', '),
                    fileExt = self.allowedFileExtensions, strExt = isEmpty(fileExt) ? '' : fileExt.join(', ');
```

Is it me only?
If this is a stupid problem, sorry for advance.

Thanks!

**Comment by kartik-v** [comment]
You need to check (and debug) your code for other Javascript errors/dependencies on your page. 
Since your use case is specific to your environment and cannot reproduce... you may need to do the debuggin.
Try just to create a fresh TEST page with just this plugin (and its pre-requisites) loaded and no other third party JS, scripts or plugins  - and work from there.
