### ISSUE TITLE
Upload files one at a time.

### ISSUE THREAD

**Issue by websanova** [kartik-v/bootstrap-fileinput#608]
Doesn't seem to be an option to simply upload files one at a time when batch selecting.

Need to select a batch of files, send them one at a time and run a callback after each upload.

I don't want to do synchronous batch upload with all the files at once. Need it just one at a time.

Not sure if there is a way to do this, but doesn't seem so .

**Comment by kartik-v** [comment]
You may want to read the docs and go through usage demos to see and achieve your use case.

The plugin supports [asynchronous or parallel ajax uploads for each file separately](http://plugins.krajee.com/file-input#ajax-async).

**Comment by im-SRK** [comment]
Excellent work kartik!

In case of uploading multiple files, some files do not upload showing error 

> Something went wrong with file upload operation.

Can you please guide?

I think it is because of uploading multiple files at the same time. Therefore, I also need guideline to upload async files (uploadAsync: true) but each file uploaded one by one (ie. one after another) along with individual progress bars.

Thanks
