### ISSUE TITLE
File preview glitch in Chrome

### ISSUE THREAD

**Issue by khituras** [kartik-v/bootstrap-fileinput#657]
The file previews, e.g. at http://plugins.krajee.com/file-basic-usage-demo at the very first example, exhibit a weird behavior in Chrome (Mac, Version 50.0.2661.102 (64-bit)). After selecting a text file, the preview is shown as expected. When one then clicks once on the scroll handle in the scroll bar, it will kind of stick to the cursor no matter what. Without pressing any buttons, moving the cursor inside - and sometimes even outside - of the preview will cause constant scroll towards to vertical position of the cursor. I don't observe this behaviour in FireFox. In seem in Chrome the mouse release event isn't handled or something like this.

**Comment by kartik-v** [comment]
This is a Chrome specific behavior and occurs only for the OBJECT type of markup (where files are embedded based on default template for `previewTemplates.object`).

For text files (e.g. files with `.txt`, `.md` and such other extensions)... the plugin now uses a different template with just a div and text area - so this should not happen. So I should assume this is the fix for your case.

If you are using unknown file types... the plugin defaults to the object embedding template... a workaround is to change the preview template for `object` type of files... OR you can configure which types of files can be previewed via `previewSettings`
