### ISSUE TITLE
Video Preview Is Not Displayed

### ISSUE THREAD

**Issue by cansozeri** [kartik-v/bootstrap-fileinput#720]
Hi,

I am using fileinput 4.1.8 (ajax upload ) and the preview of a video file is working like a charm. I can watch video before I uploaded the file. But when I updated to the latest version, the video preview is not working. There is no playback option or a video player to preview the video. Is there any additional setting for this ?? But in your site demos the video preview is not working too if I select a mp4 video from my computer.

**Comment by cansozeri** [comment]
If I use your small mp4, the preview works, but If I use a larger video from Youtube (44 MB), the video preview is not working ..

**Comment by kartik-v** [comment]
Cannot reproduce what you are saying... but display of video depends on HTML5 video tag support by your browser and supported file types (browser memory is also important).

You may need to check if you are running exactly same builds as you mentioned because there is no difference in video preview templates for the versions mentioned.

Can you share a working JS Fiddle to show the differences you pointed out?

**Comment by yucolabjames** [comment]
I can reproduce the problem described by @cansozeri  it seems like files bigger than 13MB would not be playable in the preview. It doesn't seem to have anything to do with `maxFileSize` since we allow up to 1024MB uploads. 

Could it be a Chrome preloading meta data behaviour for large files?
