### ISSUE TITLE
HTTP Error 405.0 - Method Not Allowed

### ISSUE THREAD

**Issue by biglat** [kartik-v/bootstrap-fileinput#797]
Hi,
Thanks for your Plugins,
I Have HTTP Error 405.0 - Method Not Allowed on Ajax Upload.
So Please Help Me To Resolve it

**Comment by simoratax** [comment]
in node js


2016-11-11 8:13 GMT+00:00 biglat <notifications@github.com>:

**Comment by simoratax** [comment]
or php

2016-11-11 23:41 GMT+00:00 MED Zarr <zarrouki1991@gmail.com>:

**Comment by biglat** [comment]
In Asp.Net

**Comment by kartik-v** [comment]
You need to check your server code and/or web server configuration. For example [check this article for ASP.NET](http://stackoverflow.com/questions/13258014/jquery-post-error-405-method-not-allowed).

**Comment by marioene** [comment]
I implemented this great plugin in my Laravel projects (PHP)
For AjaxUpload or AjaxDelete methods I got the same error when my routes 
were declared with Route::get. When I change to Route::post the 2 methods were working perfectly.

A part of my routes\web.php in Laravel 5.3:

`
Route::post('ajax_UploadImage', 'Dashboard\AjaxController@ajax_UploadImage');
Route::post('ajax_DeleteImagineAnunt/{id_anunt}', 'Dashboard\AjaxController@ajax_DeleteImage');
`

**Comment by kartik-v** [comment]
@marioene That is because the default method for handling ajax requests is set to POST for upload and delete in [`ajaxSettings`](http://plugins.krajee.com/file-input#option-ajaxsettings) and [`ajaxDeleteSettings`](http://plugins.krajee.com/file-input#option-ajaxdeletesettings] respectively.

You need to control these settings and set it to GET if you need GET requests... in either case all these are a part of your app design and security needs.
