### ISSUE TITLE
filePreview

### ISSUE THREAD

**Issue by pavilandoangelo** [kartik-v/bootstrap-fileinput#843]
How to get the data of file preview items?

**Comment by maodei** [comment]
var files = $('#input-id').fileinput('getFileStack'); // returns file list selected

**Comment by kartik-v** [comment]
Yes because getfilestack is only to return list of files selected on client.

The initial preview is just a display and links and not file blobs. You already have your initial preview data on your server which is used to generate initial preview.

You can get displayed initial preview don client by parsing thumbnails with CSS class 'file-preview-frame' and checking '.kv-file-content'.
