### ISSUE TITLE
FileExtension not allowed only shows if caption is set to true. Should be always visible. 

### ISSUE THREAD

**Issue by pedroadame** [kartik-v/bootstrap-fileinput#873]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Create a basic bootstrap fileinput
2. Set `showUpload: false` and `showCaption: false`
3. Set `allowedFileTypeExtensions` to something `['pdf']` for example.
4. Set `language` to `es` (after loading locales/es.js obviously)
4. Try to upload a NOT allowed file.

## Expected behavior and actual behavior
When I follow those steps, I see...
- Nothing but an exclamation in the input file name field
- The "delete" button.

If I don't set language, the delete button shows and a red text "no files selected" is shown.

I was expecting...
- The message that shows in the caption showed up right before the fileinput
- Not having to press "delete" unless the filename appeared in the fileinput filename field. 

If I don't set language: The alert should be shown and the delete file button shouldn't. Also, the file should be unselected automatically
## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [x] Safari

Operating System

- [ ] Windows - Not tested
- [ ] Mac OS X - Not tested
- [x] Linux - Not tested
- [ ] Mobile - Not tested

Libraries

- jQuery version: 3.1.1
- bootstrap-fileinput version: master

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/bifome/1/edit?output)

**Comment by kartik-v** [comment]
This is expected ... Since you have set `showCaption` to `false` it means you do not want caption to be displayed and hence anything supposed to be displayed in caption will not be displayed.

If you need to set your own caption markup... then do not set `showCaption` to false... instead set up your own markup for caption container and set the property [elCaptionContainer](http://plugins.krajee.com/file-input#option-elcaptioncontainer) to point to the id or CSS class selector for this container...

```html
<div id="myCustomCap"></div> <!-- your custom caption container -->
<input type="file" id="myFileInput" name="myFileInput[]" multiple>
<script>
$('#myFileInput').fileinput({
    elCaptionContainer: '#myCustomCap'
});
</script>
```

**Comment by pedroadame** [comment]
Well... at least I think that when you set caption to false it should display "Invalid file" as the error message because "No selected files" is a little bit confusing since you have to delete the file you uploaded. I used this modifying the locale as a workaround.

**Comment by kartik-v** [comment]
I am not clear on your query... already the error message shown when `allowedFileExtensions` is set and validated is determined by [msgInvalidFileExtension](http://plugins.krajee.com/file-input#option-msginvalidfileextension), which defaults to 

```
Invalid extension for file "{name}". Only "{extensions}" files are supported.
```

**Comment by kartik-v** [comment]
Check [advanced demo example # 5](http://plugins.krajee.com/file-advanced-usage-demo#advanced-example-5) for an usage of allowed file extensions validation and the error message shown...

**Comment by pedroadame** [comment]
Sorry it was a typo in the issue. In my code there is `allowedFileExtensions`.
The point is that I do not want caption but I want an error message. To workaround this, all I needed to do is change `msgNoFilesSelected` (shown in the "file" field when a not allowed file is selected, and then you have to press "delete") to "Invalid file", so the user knows he need to delete the selected file. Btw, this string is not set in the "es" locale. Should be "No hay archivos seleccionados".

**Comment by kartik-v** [comment]
No the understanding is not correct. These are two different messages for two different reasons:

- [msgInvalidFileExtension](http://plugins.krajee.com/file-input#option-msginvalidfileextension): This message is shown as an error message. As explained before, this is the error message shown when `allowedFileExtensions` error is faced
-  [msgNoFilesSelected](http://plugins.krajee.com/file-input#option-msgnofilesselected): This message is shown within the caption field. The `msgNoFilesSelected` is shown in the caption when no files are selected by the last action... and this can happen due to various reasons (not necessarily only due to `allowedFileExtensions` error).

**Comment by kartik-v** [comment]
> Btw, this string is not set in the "es" locale. Should be "No hay archivos seleccionados".

Can you submit a PR for this for the `es` translation.

**Comment by kartik-v** [comment]
> Btw, this string is not set in the "es" locale. Should be "No hay archivos seleccionados".

Can you submit a PR for this for the `es` translation? Let know if the messages can be improved.
