### ISSUE TITLE
Disable animation when selecting many files

### ISSUE THREAD

**Issue by nWidart** [kartik-v/bootstrap-fileinput#884]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Select 300+ images/files, and click upload
2. There will now be an animation that takes a very long time, adding each image/file one by one

## Expected

Is there a way to remove this animation, and to just have the 300+ images/files be added instantly ?

## Environment

Browsers

Same effect on all browsers.

Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: jQuery-2.1.4
- bootstrap-fileinput version: 4.3.6

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo) Basic example 3 (multiple upload)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by nWidart** [comment]
Setting `showPreview` to false, removes the animation, however it also removes the preview images. I'm guessing now the time it takes to load in all images, is the time to create the preview ?

**Comment by kartik-v** [comment]
Yes ... it is not animation ... but creating the preview will take time depending on number of files and size/data of each file... since browser needs to read each file data and display it. You can choose to set - 

- `showPreview` to false if you do not need this time to wait... OR 
- with `showPreview` to true alternatively restrict and set [`allowedPreviewTypes`](http://localhost/plugins/file-input#option-allowedpreviewtypes) to only show preview for certain files and set others to not display content
- or similarly like above set [`allowedPreviewMimeTypes`](http://localhost/plugins/file-input#option-allowedpreviewmimetypes)
