### ISSUE TITLE
How to change the upload address

### ISSUE THREAD

**Issue by ailley** [kartik-v/bootstrap-fileinput#888]
### I changed the uploadUrl to a new value but the upload is still the last time the value of how to change the uploadUrl re submit

**Comment by ailley** [comment]
![image](https://cloud.githubusercontent.com/assets/16378656/23454523/8150ee4c-fea7-11e6-968a-6c4101bb8fd5.png)
![image](https://cloud.githubusercontent.com/assets/16378656/23454611/c7eec586-fea7-11e6-8218-c36a5f394966.png)

## No parameter values when uploading

**Comment by kartik-v** [comment]
Suggest to use POST instead of GET params to append to your upload URL... you can send parameters to your uploadUrl using `uploadExtraData`.

You can send dynamic data for `uploadExtraData` by setting  a JS function callback as described in [documentation for uploadExtraData](http://plugins.krajee.com/file-input#option-uploadextradata).
