### ISSUE TITLE
Server throwing 500 not being caught in error events

### ISSUE THREAD

**Issue by zoinkydoink** [kartik-v/bootstrap-fileinput#951]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

Setup the following

`function setupUploader() {
    var importResults = $("#import-results");

    $import_prayer_times_input.fileinput({
        uploadUrl: "/member/uploadprayersfile",
        showPreview: false,
        msgAjaxError: "testing",
        uploadAsync: true,
        maxFileCount: 1,
        allowedFileExtensions: ["txt", "csv", "xls", "xlsx"]
    }).on('fileerror', (event, data, msg) => {
        showHtmlError("Upload Error", msg);
        importResults.hide();
    }).on('filebatchselected', (event, data, msg) => {
        $import_prayer_times_input.fileinput("upload");
    }).on('fileuploaded', (event, data, previewId, index) => {
        console.log("success upload");
        $import_prayer_times_input.fileinput('clear').fileinput('cancel').fileinput("unlock");
        if (data.response) {
            prayerImportUploaded(data.response, importResults);
        }
        else {
            showHtmlError("Upload Error", "Upload did not work, try again");
        }
    }).on('fileuploaderror ', (event, data, msg) => {
        console.log("error");
        showHtmlError("Upload Error", msg);
        importResults.hide();
    }).on('filebatchuploaderror ', (event, data, msg) => {
        console.log("error");
        showHtmlError("Upload Error", msg);
        importResults.hide();
    });
}
`

## Expected behavior and actual behavior
I expect either fileuploaderror or filebatchuploaderror to fired or maybe another event that is specific to server errors

The file uploads fine (I can debug and see the file) however when in my server side code i open the file, the file content is bad and i am raising a 500 hoping that some client side method will fire so i can show user a generic message

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [x] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 2.1.4
- bootstrap-fileinput version:  4.39 and 4.4

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Server errors would be automatically displayed based on `showAjaxErrorDetails` boolean setting. You should be able to use `fileuploaderror` and `filebatchuploaderror` as error events for your use case.

Not sure what is the issue - can you share a demo link?

**Comment by silencehe09** [comment]
I have met the same problem too.
Steps to reproduce the issue:
(1) html
<div class="file-loading">
      <input type="file" id="my-file" name="my-file" >
</div>
(2) fileinput init option
$("#my-file").fileinput(
{
      uploadUrl: "/file/upload",
      showPreview: false,  
      maxFileCount: 1
}
);
(3) When uploading a file,  if the response from server is not a valid JSON object, but exception stacktrace messages with status code 500,  the server error can't be handled correctly. The reasons are :
a.  "showPreview" is set to false  (That's why the bug exists)
b.  line 1996 in fileinput.js :  
if(self.showPreview)
{
    $thumb=$('#'+ previewId+':not(.file-preview-initial)');  // only when showPreview is true, $thumb would be initialized.
    //...other code
}
c. line 2147 in fileinput.js:   error occurs  "$thumb is undefined"
self._setPreviewError($thumb, i, self.filestack[i], self.retryErrorUploads);

**Comment by kartik-v** [comment]
If you have `showPreview` set to `false` you would need to set your own error container to allow the plugin to display errors in the error container (because error container by default is part of the preview container which you have chosen to be not rendered now with `showPreview` set to `false`). You can do this by setting [elErrorContainer](http://plugins.krajee.com/file-input#option-elerrorcontainer) as [seen in this example](http://plugins.krajee.com/file-basic-usage-demo#basic-example-9).

**Comment by kartik-v** [comment]
You may want to read all the plugin options in the documentation. If you have `showPreview` set to `false` you would need to set your own error container to allow the plugin to display errors in the error container (because error container by default is part of the preview container which you have chosen to hide with `showPreview` set to `false`). 

You can for `showPreview` set to `false` set your own error container by setting... [elErrorContainer](http://plugins.krajee.com/file-input#option-elerrorcontainer) (read about it). You can see how as [seen in this avatar demo example](http://plugins.krajee.com/file-avatar-upload-demo) or  [this demo example](http://plugins.krajee.com/file-basic-usage-demo#basic-example-9).
